// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/payment_method/v1/payment_method.proto

package paymentmethodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethodType represents the type of payment method
type PaymentMethodType int32

const (
	PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED PaymentMethodType = 0
	PaymentMethodType_PAYMENT_METHOD_TYPE_CREDIT_CARD PaymentMethodType = 1
	PaymentMethodType_PAYMENT_METHOD_TYPE_ACH         PaymentMethodType = 2
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0: "PAYMENT_METHOD_TYPE_UNSPECIFIED",
		1: "PAYMENT_METHOD_TYPE_CREDIT_CARD",
		2: "PAYMENT_METHOD_TYPE_ACH",
	}
	PaymentMethodType_value = map[string]int32{
		"PAYMENT_METHOD_TYPE_UNSPECIFIED": 0,
		"PAYMENT_METHOD_TYPE_CREDIT_CARD": 1,
		"PAYMENT_METHOD_TYPE_ACH":         2,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_method_v1_payment_method_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_proto_payment_method_v1_payment_method_proto_enumTypes[0]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{0}
}

// AccountType for ACH accounts
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_CHECKING    AccountType = 1
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_CHECKING",
		2: "ACCOUNT_TYPE_SAVINGS",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_CHECKING":    1,
		"ACCOUNT_TYPE_SAVINGS":     2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_method_v1_payment_method_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_payment_method_v1_payment_method_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{1}
}

// StdEntryClass for ACH transactions
type StdEntryClass int32

const (
	StdEntryClass_STD_ENTRY_CLASS_UNSPECIFIED StdEntryClass = 0
	StdEntryClass_STD_ENTRY_CLASS_PPD         StdEntryClass = 1 // Prearranged Payment and Deposit (personal)
	StdEntryClass_STD_ENTRY_CLASS_CCD         StdEntryClass = 2 // Corporate Credit or Debit
	StdEntryClass_STD_ENTRY_CLASS_WEB         StdEntryClass = 3 // Internet-initiated entry
	StdEntryClass_STD_ENTRY_CLASS_TEL         StdEntryClass = 4 // Telephone-initiated entry
)

// Enum value maps for StdEntryClass.
var (
	StdEntryClass_name = map[int32]string{
		0: "STD_ENTRY_CLASS_UNSPECIFIED",
		1: "STD_ENTRY_CLASS_PPD",
		2: "STD_ENTRY_CLASS_CCD",
		3: "STD_ENTRY_CLASS_WEB",
		4: "STD_ENTRY_CLASS_TEL",
	}
	StdEntryClass_value = map[string]int32{
		"STD_ENTRY_CLASS_UNSPECIFIED": 0,
		"STD_ENTRY_CLASS_PPD":         1,
		"STD_ENTRY_CLASS_CCD":         2,
		"STD_ENTRY_CLASS_WEB":         3,
		"STD_ENTRY_CLASS_TEL":         4,
	}
)

func (x StdEntryClass) Enum() *StdEntryClass {
	p := new(StdEntryClass)
	*p = x
	return p
}

func (x StdEntryClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StdEntryClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_method_v1_payment_method_proto_enumTypes[2].Descriptor()
}

func (StdEntryClass) Type() protoreflect.EnumType {
	return &file_proto_payment_method_v1_payment_method_proto_enumTypes[2]
}

func (x StdEntryClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StdEntryClass.Descriptor instead.
func (StdEntryClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{2}
}

// GetPaymentMethodRequest retrieves a payment method
type GetPaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"` // UUID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPaymentMethodRequest) Reset() {
	*x = GetPaymentMethodRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodRequest) ProtoMessage() {}

func (x *GetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

// ListPaymentMethodsRequest lists payment methods
type ListPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentType   *PaymentMethodType     `protobuf:"varint,3,opt,name=payment_type,json=paymentType,proto3,enum=payment_method.v1.PaymentMethodType,oneof" json:"payment_type,omitempty"` // Optional: filter by type
	IsActive      *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`                                                   // Optional: filter by active status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentMethodsRequest) Reset() {
	*x = ListPaymentMethodsRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsRequest) ProtoMessage() {}

func (x *ListPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{1}
}

func (x *ListPaymentMethodsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListPaymentMethodsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPaymentMethodsRequest) GetPaymentType() PaymentMethodType {
	if x != nil && x.PaymentType != nil {
		return *x.PaymentType
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *ListPaymentMethodsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// ListPaymentMethodsResponse contains payment method list
type ListPaymentMethodsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethods []*PaymentMethod       `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPaymentMethodsResponse) Reset() {
	*x = ListPaymentMethodsResponse{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsResponse) ProtoMessage() {}

func (x *ListPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

// UpdatePaymentMethodStatusRequest updates payment method status
type UpdatePaymentMethodStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IsActive        bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // true = activate, false = deactivate
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePaymentMethodStatusRequest) Reset() {
	*x = UpdatePaymentMethodStatusRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentMethodStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentMethodStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentMethodStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentMethodStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentMethodStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePaymentMethodStatusRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *UpdatePaymentMethodStatusRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdatePaymentMethodStatusRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdatePaymentMethodStatusRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// DeletePaymentMethodRequest soft deletes a payment method
type DeletePaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeletePaymentMethodRequest) Reset() {
	*x = DeletePaymentMethodRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentMethodRequest) ProtoMessage() {}

func (x *DeletePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *DeletePaymentMethodRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// DeletePaymentMethodResponse confirms deletion
type DeletePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentMethodResponse) Reset() {
	*x = DeletePaymentMethodResponse{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentMethodResponse) ProtoMessage() {}

func (x *DeletePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePaymentMethodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePaymentMethodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SetDefaultPaymentMethodRequest sets default payment method
type SetDefaultPaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDefaultPaymentMethodRequest) Reset() {
	*x = SetDefaultPaymentMethodRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultPaymentMethodRequest) ProtoMessage() {}

func (x *SetDefaultPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{6}
}

func (x *SetDefaultPaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *SetDefaultPaymentMethodRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SetDefaultPaymentMethodRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// VerifyACHAccountRequest initiates ACH verification
type VerifyACHAccountRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"` // ACH payment method to verify
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyACHAccountRequest) Reset() {
	*x = VerifyACHAccountRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyACHAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyACHAccountRequest) ProtoMessage() {}

func (x *VerifyACHAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyACHAccountRequest.ProtoReflect.Descriptor instead.
func (*VerifyACHAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyACHAccountRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *VerifyACHAccountRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *VerifyACHAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// VerifyACHAccountResponse contains verification status
type VerifyACHAccountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Pre-note transaction ID
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                    // "pending", "verified", "failed"
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyACHAccountResponse) Reset() {
	*x = VerifyACHAccountResponse{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyACHAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyACHAccountResponse) ProtoMessage() {}

func (x *VerifyACHAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyACHAccountResponse.ProtoReflect.Descriptor instead.
func (*VerifyACHAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyACHAccountResponse) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *VerifyACHAccountResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyACHAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyACHAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StoreACHAccountRequest creates ACH Storage BRIC
type StoreACHAccountRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MerchantId string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Raw ACH account details (backend receives from customer)
	AccountNumber     string        `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	RoutingNumber     string        `protobuf:"bytes,4,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	AccountHolderName string        `protobuf:"bytes,5,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	AccountType       AccountType   `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=payment_method.v1.AccountType" json:"account_type,omitempty"`           // CHECKING or SAVINGS
	StdEntryClass     StdEntryClass `protobuf:"varint,7,opt,name=std_entry_class,json=stdEntryClass,proto3,enum=payment_method.v1.StdEntryClass" json:"std_entry_class,omitempty"` // PPD, CCD, WEB, TEL
	// Billing information (optional but recommended)
	FirstName *string `protobuf:"bytes,8,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName  *string `protobuf:"bytes,9,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Address   *string `protobuf:"bytes,10,opt,name=address,proto3,oneof" json:"address,omitempty"`
	City      *string `protobuf:"bytes,11,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State     *string `protobuf:"bytes,12,opt,name=state,proto3,oneof" json:"state,omitempty"`
	ZipCode   *string `protobuf:"bytes,13,opt,name=zip_code,json=zipCode,proto3,oneof" json:"zip_code,omitempty"`
	// Display metadata (optional)
	BankName       *string `protobuf:"bytes,14,opt,name=bank_name,json=bankName,proto3,oneof" json:"bank_name,omitempty"` // "Chase", "Bank of America"
	Nickname       *string `protobuf:"bytes,15,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`                 // "Primary checking", "Business account"
	IsDefault      bool    `protobuf:"varint,16,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	IdempotencyKey string  `protobuf:"bytes,17,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreACHAccountRequest) Reset() {
	*x = StoreACHAccountRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreACHAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreACHAccountRequest) ProtoMessage() {}

func (x *StoreACHAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreACHAccountRequest.ProtoReflect.Descriptor instead.
func (*StoreACHAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{9}
}

func (x *StoreACHAccountRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *StoreACHAccountRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *StoreACHAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *StoreACHAccountRequest) GetRoutingNumber() string {
	if x != nil {
		return x.RoutingNumber
	}
	return ""
}

func (x *StoreACHAccountRequest) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *StoreACHAccountRequest) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *StoreACHAccountRequest) GetStdEntryClass() StdEntryClass {
	if x != nil {
		return x.StdEntryClass
	}
	return StdEntryClass_STD_ENTRY_CLASS_UNSPECIFIED
}

func (x *StoreACHAccountRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *StoreACHAccountRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *StoreACHAccountRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *StoreACHAccountRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *StoreACHAccountRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *StoreACHAccountRequest) GetZipCode() string {
	if x != nil && x.ZipCode != nil {
		return *x.ZipCode
	}
	return ""
}

func (x *StoreACHAccountRequest) GetBankName() string {
	if x != nil && x.BankName != nil {
		return *x.BankName
	}
	return ""
}

func (x *StoreACHAccountRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *StoreACHAccountRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *StoreACHAccountRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// UpdatePaymentMethodRequest updates metadata only
// Does NOT support changing account/routing numbers, card numbers, etc.
// For account changes, delete old payment method and create new one
type UpdatePaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Metadata updates (all optional)
	BillingName    *string `protobuf:"bytes,4,opt,name=billing_name,json=billingName,proto3,oneof" json:"billing_name,omitempty"`
	BillingAddress *string `protobuf:"bytes,5,opt,name=billing_address,json=billingAddress,proto3,oneof" json:"billing_address,omitempty"`
	BillingCity    *string `protobuf:"bytes,6,opt,name=billing_city,json=billingCity,proto3,oneof" json:"billing_city,omitempty"`
	BillingState   *string `protobuf:"bytes,7,opt,name=billing_state,json=billingState,proto3,oneof" json:"billing_state,omitempty"`
	BillingZip     *string `protobuf:"bytes,8,opt,name=billing_zip,json=billingZip,proto3,oneof" json:"billing_zip,omitempty"`
	Nickname       *string `protobuf:"bytes,9,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	IsDefault      *bool   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	IdempotencyKey string  `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePaymentMethodRequest) Reset() {
	*x = UpdatePaymentMethodRequest{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentMethodRequest) ProtoMessage() {}

func (x *UpdatePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetBillingName() string {
	if x != nil && x.BillingName != nil {
		return *x.BillingName
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetBillingAddress() string {
	if x != nil && x.BillingAddress != nil {
		return *x.BillingAddress
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetBillingCity() string {
	if x != nil && x.BillingCity != nil {
		return *x.BillingCity
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetBillingState() string {
	if x != nil && x.BillingState != nil {
		return *x.BillingState
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetBillingZip() string {
	if x != nil && x.BillingZip != nil {
		return *x.BillingZip
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdatePaymentMethodRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *UpdatePaymentMethodRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// PaymentMethodResponse is returned from payment method operations
type PaymentMethodResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentType     PaymentMethodType      `protobuf:"varint,4,opt,name=payment_type,json=paymentType,proto3,enum=payment_method.v1.PaymentMethodType" json:"payment_type,omitempty"`
	// Display metadata
	LastFour string `protobuf:"bytes,5,opt,name=last_four,json=lastFour,proto3" json:"last_four,omitempty"`
	// Credit card specific
	CardBrand    *string `protobuf:"bytes,6,opt,name=card_brand,json=cardBrand,proto3,oneof" json:"card_brand,omitempty"`
	CardExpMonth *int32  `protobuf:"varint,7,opt,name=card_exp_month,json=cardExpMonth,proto3,oneof" json:"card_exp_month,omitempty"`
	CardExpYear  *int32  `protobuf:"varint,8,opt,name=card_exp_year,json=cardExpYear,proto3,oneof" json:"card_exp_year,omitempty"`
	// ACH specific
	BankName    *string `protobuf:"bytes,9,opt,name=bank_name,json=bankName,proto3,oneof" json:"bank_name,omitempty"`
	AccountType *string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3,oneof" json:"account_type,omitempty"`
	// Status
	IsDefault     bool                   `protobuf:"varint,11,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	IsActive      bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsVerified    bool                   `protobuf:"varint,13,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"` // For ACH pre-note verification
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethodResponse) Reset() {
	*x = PaymentMethodResponse{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodResponse) ProtoMessage() {}

func (x *PaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*PaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentMethodResponse) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *PaymentMethodResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *PaymentMethodResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PaymentMethodResponse) GetPaymentType() PaymentMethodType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *PaymentMethodResponse) GetLastFour() string {
	if x != nil {
		return x.LastFour
	}
	return ""
}

func (x *PaymentMethodResponse) GetCardBrand() string {
	if x != nil && x.CardBrand != nil {
		return *x.CardBrand
	}
	return ""
}

func (x *PaymentMethodResponse) GetCardExpMonth() int32 {
	if x != nil && x.CardExpMonth != nil {
		return *x.CardExpMonth
	}
	return 0
}

func (x *PaymentMethodResponse) GetCardExpYear() int32 {
	if x != nil && x.CardExpYear != nil {
		return *x.CardExpYear
	}
	return 0
}

func (x *PaymentMethodResponse) GetBankName() string {
	if x != nil && x.BankName != nil {
		return *x.BankName
	}
	return ""
}

func (x *PaymentMethodResponse) GetAccountType() string {
	if x != nil && x.AccountType != nil {
		return *x.AccountType
	}
	return ""
}

func (x *PaymentMethodResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *PaymentMethodResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PaymentMethodResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *PaymentMethodResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentMethodResponse) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// PaymentMethod represents a complete payment method record
type PaymentMethod struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId  string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId  string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PaymentType PaymentMethodType      `protobuf:"varint,4,opt,name=payment_type,json=paymentType,proto3,enum=payment_method.v1.PaymentMethodType" json:"payment_type,omitempty"`
	// Display metadata (NEVER include full card/account numbers)
	LastFour string `protobuf:"bytes,5,opt,name=last_four,json=lastFour,proto3" json:"last_four,omitempty"`
	// Credit card specific
	CardBrand    *string `protobuf:"bytes,6,opt,name=card_brand,json=cardBrand,proto3,oneof" json:"card_brand,omitempty"`
	CardExpMonth *int32  `protobuf:"varint,7,opt,name=card_exp_month,json=cardExpMonth,proto3,oneof" json:"card_exp_month,omitempty"`
	CardExpYear  *int32  `protobuf:"varint,8,opt,name=card_exp_year,json=cardExpYear,proto3,oneof" json:"card_exp_year,omitempty"`
	// ACH specific
	BankName    *string `protobuf:"bytes,9,opt,name=bank_name,json=bankName,proto3,oneof" json:"bank_name,omitempty"`
	AccountType *string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3,oneof" json:"account_type,omitempty"`
	// Status
	IsDefault     bool                   `protobuf:"varint,11,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	IsActive      bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsVerified    bool                   `protobuf:"varint,13,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_method_v1_payment_method_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_proto_payment_method_v1_payment_method_proto_rawDescGZIP(), []int{12}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *PaymentMethod) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PaymentMethod) GetPaymentType() PaymentMethodType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *PaymentMethod) GetLastFour() string {
	if x != nil {
		return x.LastFour
	}
	return ""
}

func (x *PaymentMethod) GetCardBrand() string {
	if x != nil && x.CardBrand != nil {
		return *x.CardBrand
	}
	return ""
}

func (x *PaymentMethod) GetCardExpMonth() int32 {
	if x != nil && x.CardExpMonth != nil {
		return *x.CardExpMonth
	}
	return 0
}

func (x *PaymentMethod) GetCardExpYear() int32 {
	if x != nil && x.CardExpYear != nil {
		return *x.CardExpYear
	}
	return 0
}

func (x *PaymentMethod) GetBankName() string {
	if x != nil && x.BankName != nil {
		return *x.BankName
	}
	return ""
}

func (x *PaymentMethod) GetAccountType() string {
	if x != nil && x.AccountType != nil {
		return *x.AccountType
	}
	return ""
}

func (x *PaymentMethod) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *PaymentMethod) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PaymentMethod) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *PaymentMethod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentMethod) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PaymentMethod) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

var File_proto_payment_method_v1_payment_method_proto protoreflect.FileDescriptor

const file_proto_payment_method_v1_payment_method_proto_rawDesc = "" +
	"\n" +
	",proto/payment_method/v1/payment_method.proto\x12\x11payment_method.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x17GetPaymentMethodRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\"\xec\x01\n" +
	"\x19ListPaymentMethodsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12L\n" +
	"\fpayment_type\x18\x03 \x01(\x0e2$.payment_method.v1.PaymentMethodTypeH\x00R\vpaymentType\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x04 \x01(\bH\x01R\bisActive\x88\x01\x01B\x0f\n" +
	"\r_payment_typeB\f\n" +
	"\n" +
	"_is_active\"g\n" +
	"\x1aListPaymentMethodsResponse\x12I\n" +
	"\x0fpayment_methods\x18\x01 \x03(\v2 .payment_method.v1.PaymentMethodR\x0epaymentMethods\"\xad\x01\n" +
	" UpdatePaymentMethodStatusRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"q\n" +
	"\x1aDeletePaymentMethodRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"Q\n" +
	"\x1bDeletePaymentMethodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x1eSetDefaultPaymentMethodRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\"\x87\x01\n" +
	"\x17VerifyACHAccountRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\"\x9f\x01\n" +
	"\x18VerifyACHAccountResponse\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x8d\x06\n" +
	"\x16StoreACHAccountRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12%\n" +
	"\x0erouting_number\x18\x04 \x01(\tR\rroutingNumber\x12.\n" +
	"\x13account_holder_name\x18\x05 \x01(\tR\x11accountHolderName\x12A\n" +
	"\faccount_type\x18\x06 \x01(\x0e2\x1e.payment_method.v1.AccountTypeR\vaccountType\x12H\n" +
	"\x0fstd_entry_class\x18\a \x01(\x0e2 .payment_method.v1.StdEntryClassR\rstdEntryClass\x12\"\n" +
	"\n" +
	"first_name\x18\b \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\t \x01(\tH\x01R\blastName\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\n" +
	" \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\v \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\f \x01(\tH\x04R\x05state\x88\x01\x01\x12\x1e\n" +
	"\bzip_code\x18\r \x01(\tH\x05R\azipCode\x88\x01\x01\x12 \n" +
	"\tbank_name\x18\x0e \x01(\tH\x06R\bbankName\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x0f \x01(\tH\aR\bnickname\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_default\x18\x10 \x01(\bR\tisDefault\x12'\n" +
	"\x0fidempotency_key\x18\x11 \x01(\tR\x0eidempotencyKeyB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\v\n" +
	"\t_zip_codeB\f\n" +
	"\n" +
	"_bank_nameB\v\n" +
	"\t_nickname\"\xba\x04\n" +
	"\x1aUpdatePaymentMethodRequest\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12&\n" +
	"\fbilling_name\x18\x04 \x01(\tH\x00R\vbillingName\x88\x01\x01\x12,\n" +
	"\x0fbilling_address\x18\x05 \x01(\tH\x01R\x0ebillingAddress\x88\x01\x01\x12&\n" +
	"\fbilling_city\x18\x06 \x01(\tH\x02R\vbillingCity\x88\x01\x01\x12(\n" +
	"\rbilling_state\x18\a \x01(\tH\x03R\fbillingState\x88\x01\x01\x12$\n" +
	"\vbilling_zip\x18\b \x01(\tH\x04R\n" +
	"billingZip\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\t \x01(\tH\x05R\bnickname\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bH\x06R\tisDefault\x88\x01\x01\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKeyB\x0f\n" +
	"\r_billing_nameB\x12\n" +
	"\x10_billing_addressB\x0f\n" +
	"\r_billing_cityB\x10\n" +
	"\x0e_billing_stateB\x0e\n" +
	"\f_billing_zipB\v\n" +
	"\t_nicknameB\r\n" +
	"\v_is_default\"\xd6\x05\n" +
	"\x15PaymentMethodResponse\x12*\n" +
	"\x11payment_method_id\x18\x01 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12G\n" +
	"\fpayment_type\x18\x04 \x01(\x0e2$.payment_method.v1.PaymentMethodTypeR\vpaymentType\x12\x1b\n" +
	"\tlast_four\x18\x05 \x01(\tR\blastFour\x12\"\n" +
	"\n" +
	"card_brand\x18\x06 \x01(\tH\x00R\tcardBrand\x88\x01\x01\x12)\n" +
	"\x0ecard_exp_month\x18\a \x01(\x05H\x01R\fcardExpMonth\x88\x01\x01\x12'\n" +
	"\rcard_exp_year\x18\b \x01(\x05H\x02R\vcardExpYear\x88\x01\x01\x12 \n" +
	"\tbank_name\x18\t \x01(\tH\x03R\bbankName\x88\x01\x01\x12&\n" +
	"\faccount_type\x18\n" +
	" \x01(\tH\x04R\vaccountType\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_default\x18\v \x01(\bR\tisDefault\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_verified\x18\r \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAtB\r\n" +
	"\v_card_brandB\x11\n" +
	"\x0f_card_exp_monthB\x10\n" +
	"\x0e_card_exp_yearB\f\n" +
	"\n" +
	"_bank_nameB\x0f\n" +
	"\r_account_type\"\xed\x05\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12G\n" +
	"\fpayment_type\x18\x04 \x01(\x0e2$.payment_method.v1.PaymentMethodTypeR\vpaymentType\x12\x1b\n" +
	"\tlast_four\x18\x05 \x01(\tR\blastFour\x12\"\n" +
	"\n" +
	"card_brand\x18\x06 \x01(\tH\x00R\tcardBrand\x88\x01\x01\x12)\n" +
	"\x0ecard_exp_month\x18\a \x01(\x05H\x01R\fcardExpMonth\x88\x01\x01\x12'\n" +
	"\rcard_exp_year\x18\b \x01(\x05H\x02R\vcardExpYear\x88\x01\x01\x12 \n" +
	"\tbank_name\x18\t \x01(\tH\x03R\bbankName\x88\x01\x01\x12&\n" +
	"\faccount_type\x18\n" +
	" \x01(\tH\x04R\vaccountType\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_default\x18\v \x01(\bR\tisDefault\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_verified\x18\r \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\flast_used_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAtB\r\n" +
	"\v_card_brandB\x11\n" +
	"\x0f_card_exp_monthB\x10\n" +
	"\x0e_card_exp_yearB\f\n" +
	"\n" +
	"_bank_nameB\x0f\n" +
	"\r_account_type*z\n" +
	"\x11PaymentMethodType\x12#\n" +
	"\x1fPAYMENT_METHOD_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fPAYMENT_METHOD_TYPE_CREDIT_CARD\x10\x01\x12\x1b\n" +
	"\x17PAYMENT_METHOD_TYPE_ACH\x10\x02*`\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_TYPE_CHECKING\x10\x01\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x02*\x94\x01\n" +
	"\rStdEntryClass\x12\x1f\n" +
	"\x1bSTD_ENTRY_CLASS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STD_ENTRY_CLASS_PPD\x10\x01\x12\x17\n" +
	"\x13STD_ENTRY_CLASS_CCD\x10\x02\x12\x17\n" +
	"\x13STD_ENTRY_CLASS_WEB\x10\x03\x12\x17\n" +
	"\x13STD_ENTRY_CLASS_TEL\x10\x042\xaa\a\n" +
	"\x14PaymentMethodService\x12b\n" +
	"\x10GetPaymentMethod\x12*.payment_method.v1.GetPaymentMethodRequest\x1a .payment_method.v1.PaymentMethod\"\x00\x12s\n" +
	"\x12ListPaymentMethods\x12,.payment_method.v1.ListPaymentMethodsRequest\x1a-.payment_method.v1.ListPaymentMethodsResponse\"\x00\x12|\n" +
	"\x19UpdatePaymentMethodStatus\x123.payment_method.v1.UpdatePaymentMethodStatusRequest\x1a(.payment_method.v1.PaymentMethodResponse\"\x00\x12v\n" +
	"\x13DeletePaymentMethod\x12-.payment_method.v1.DeletePaymentMethodRequest\x1a..payment_method.v1.DeletePaymentMethodResponse\"\x00\x12x\n" +
	"\x17SetDefaultPaymentMethod\x121.payment_method.v1.SetDefaultPaymentMethodRequest\x1a(.payment_method.v1.PaymentMethodResponse\"\x00\x12m\n" +
	"\x10VerifyACHAccount\x12*.payment_method.v1.VerifyACHAccountRequest\x1a+.payment_method.v1.VerifyACHAccountResponse\"\x00\x12h\n" +
	"\x0fStoreACHAccount\x12).payment_method.v1.StoreACHAccountRequest\x1a(.payment_method.v1.PaymentMethodResponse\"\x00\x12p\n" +
	"\x13UpdatePaymentMethod\x12-.payment_method.v1.UpdatePaymentMethodRequest\x1a(.payment_method.v1.PaymentMethodResponse\"\x00BOZMgithub.com/kevin07696/payment-service/proto/payment_method/v1;paymentmethodv1b\x06proto3"

var (
	file_proto_payment_method_v1_payment_method_proto_rawDescOnce sync.Once
	file_proto_payment_method_v1_payment_method_proto_rawDescData []byte
)

func file_proto_payment_method_v1_payment_method_proto_rawDescGZIP() []byte {
	file_proto_payment_method_v1_payment_method_proto_rawDescOnce.Do(func() {
		file_proto_payment_method_v1_payment_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_method_v1_payment_method_proto_rawDesc), len(file_proto_payment_method_v1_payment_method_proto_rawDesc)))
	})
	return file_proto_payment_method_v1_payment_method_proto_rawDescData
}

var file_proto_payment_method_v1_payment_method_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_payment_method_v1_payment_method_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_payment_method_v1_payment_method_proto_goTypes = []any{
	(PaymentMethodType)(0),                   // 0: payment_method.v1.PaymentMethodType
	(AccountType)(0),                         // 1: payment_method.v1.AccountType
	(StdEntryClass)(0),                       // 2: payment_method.v1.StdEntryClass
	(*GetPaymentMethodRequest)(nil),          // 3: payment_method.v1.GetPaymentMethodRequest
	(*ListPaymentMethodsRequest)(nil),        // 4: payment_method.v1.ListPaymentMethodsRequest
	(*ListPaymentMethodsResponse)(nil),       // 5: payment_method.v1.ListPaymentMethodsResponse
	(*UpdatePaymentMethodStatusRequest)(nil), // 6: payment_method.v1.UpdatePaymentMethodStatusRequest
	(*DeletePaymentMethodRequest)(nil),       // 7: payment_method.v1.DeletePaymentMethodRequest
	(*DeletePaymentMethodResponse)(nil),      // 8: payment_method.v1.DeletePaymentMethodResponse
	(*SetDefaultPaymentMethodRequest)(nil),   // 9: payment_method.v1.SetDefaultPaymentMethodRequest
	(*VerifyACHAccountRequest)(nil),          // 10: payment_method.v1.VerifyACHAccountRequest
	(*VerifyACHAccountResponse)(nil),         // 11: payment_method.v1.VerifyACHAccountResponse
	(*StoreACHAccountRequest)(nil),           // 12: payment_method.v1.StoreACHAccountRequest
	(*UpdatePaymentMethodRequest)(nil),       // 13: payment_method.v1.UpdatePaymentMethodRequest
	(*PaymentMethodResponse)(nil),            // 14: payment_method.v1.PaymentMethodResponse
	(*PaymentMethod)(nil),                    // 15: payment_method.v1.PaymentMethod
	(*timestamppb.Timestamp)(nil),            // 16: google.protobuf.Timestamp
}
var file_proto_payment_method_v1_payment_method_proto_depIdxs = []int32{
	0,  // 0: payment_method.v1.ListPaymentMethodsRequest.payment_type:type_name -> payment_method.v1.PaymentMethodType
	15, // 1: payment_method.v1.ListPaymentMethodsResponse.payment_methods:type_name -> payment_method.v1.PaymentMethod
	1,  // 2: payment_method.v1.StoreACHAccountRequest.account_type:type_name -> payment_method.v1.AccountType
	2,  // 3: payment_method.v1.StoreACHAccountRequest.std_entry_class:type_name -> payment_method.v1.StdEntryClass
	0,  // 4: payment_method.v1.PaymentMethodResponse.payment_type:type_name -> payment_method.v1.PaymentMethodType
	16, // 5: payment_method.v1.PaymentMethodResponse.created_at:type_name -> google.protobuf.Timestamp
	16, // 6: payment_method.v1.PaymentMethodResponse.last_used_at:type_name -> google.protobuf.Timestamp
	0,  // 7: payment_method.v1.PaymentMethod.payment_type:type_name -> payment_method.v1.PaymentMethodType
	16, // 8: payment_method.v1.PaymentMethod.created_at:type_name -> google.protobuf.Timestamp
	16, // 9: payment_method.v1.PaymentMethod.updated_at:type_name -> google.protobuf.Timestamp
	16, // 10: payment_method.v1.PaymentMethod.last_used_at:type_name -> google.protobuf.Timestamp
	3,  // 11: payment_method.v1.PaymentMethodService.GetPaymentMethod:input_type -> payment_method.v1.GetPaymentMethodRequest
	4,  // 12: payment_method.v1.PaymentMethodService.ListPaymentMethods:input_type -> payment_method.v1.ListPaymentMethodsRequest
	6,  // 13: payment_method.v1.PaymentMethodService.UpdatePaymentMethodStatus:input_type -> payment_method.v1.UpdatePaymentMethodStatusRequest
	7,  // 14: payment_method.v1.PaymentMethodService.DeletePaymentMethod:input_type -> payment_method.v1.DeletePaymentMethodRequest
	9,  // 15: payment_method.v1.PaymentMethodService.SetDefaultPaymentMethod:input_type -> payment_method.v1.SetDefaultPaymentMethodRequest
	10, // 16: payment_method.v1.PaymentMethodService.VerifyACHAccount:input_type -> payment_method.v1.VerifyACHAccountRequest
	12, // 17: payment_method.v1.PaymentMethodService.StoreACHAccount:input_type -> payment_method.v1.StoreACHAccountRequest
	13, // 18: payment_method.v1.PaymentMethodService.UpdatePaymentMethod:input_type -> payment_method.v1.UpdatePaymentMethodRequest
	15, // 19: payment_method.v1.PaymentMethodService.GetPaymentMethod:output_type -> payment_method.v1.PaymentMethod
	5,  // 20: payment_method.v1.PaymentMethodService.ListPaymentMethods:output_type -> payment_method.v1.ListPaymentMethodsResponse
	14, // 21: payment_method.v1.PaymentMethodService.UpdatePaymentMethodStatus:output_type -> payment_method.v1.PaymentMethodResponse
	8,  // 22: payment_method.v1.PaymentMethodService.DeletePaymentMethod:output_type -> payment_method.v1.DeletePaymentMethodResponse
	14, // 23: payment_method.v1.PaymentMethodService.SetDefaultPaymentMethod:output_type -> payment_method.v1.PaymentMethodResponse
	11, // 24: payment_method.v1.PaymentMethodService.VerifyACHAccount:output_type -> payment_method.v1.VerifyACHAccountResponse
	14, // 25: payment_method.v1.PaymentMethodService.StoreACHAccount:output_type -> payment_method.v1.PaymentMethodResponse
	14, // 26: payment_method.v1.PaymentMethodService.UpdatePaymentMethod:output_type -> payment_method.v1.PaymentMethodResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_payment_method_v1_payment_method_proto_init() }
func file_proto_payment_method_v1_payment_method_proto_init() {
	if File_proto_payment_method_v1_payment_method_proto != nil {
		return
	}
	file_proto_payment_method_v1_payment_method_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_payment_method_v1_payment_method_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_payment_method_v1_payment_method_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_payment_method_v1_payment_method_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_payment_method_v1_payment_method_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_method_v1_payment_method_proto_rawDesc), len(file_proto_payment_method_v1_payment_method_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_method_v1_payment_method_proto_goTypes,
		DependencyIndexes: file_proto_payment_method_v1_payment_method_proto_depIdxs,
		EnumInfos:         file_proto_payment_method_v1_payment_method_proto_enumTypes,
		MessageInfos:      file_proto_payment_method_v1_payment_method_proto_msgTypes,
	}.Build()
	File_proto_payment_method_v1_payment_method_proto = out.File
	file_proto_payment_method_v1_payment_method_proto_goTypes = nil
	file_proto_payment_method_v1_payment_method_proto_depIdxs = nil
}
