// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/payment/v1/payment.proto

package paymentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kevin07696/payment-service/proto/payment/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentServiceName is the fully-qualified name of the PaymentService service.
	PaymentServiceName = "payment.v1.PaymentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentServiceAuthorizeProcedure is the fully-qualified name of the PaymentService's Authorize
	// RPC.
	PaymentServiceAuthorizeProcedure = "/payment.v1.PaymentService/Authorize"
	// PaymentServiceCaptureProcedure is the fully-qualified name of the PaymentService's Capture RPC.
	PaymentServiceCaptureProcedure = "/payment.v1.PaymentService/Capture"
	// PaymentServiceSaleProcedure is the fully-qualified name of the PaymentService's Sale RPC.
	PaymentServiceSaleProcedure = "/payment.v1.PaymentService/Sale"
	// PaymentServiceVoidProcedure is the fully-qualified name of the PaymentService's Void RPC.
	PaymentServiceVoidProcedure = "/payment.v1.PaymentService/Void"
	// PaymentServiceRefundProcedure is the fully-qualified name of the PaymentService's Refund RPC.
	PaymentServiceRefundProcedure = "/payment.v1.PaymentService/Refund"
	// PaymentServiceGetTransactionProcedure is the fully-qualified name of the PaymentService's
	// GetTransaction RPC.
	PaymentServiceGetTransactionProcedure = "/payment.v1.PaymentService/GetTransaction"
	// PaymentServiceListTransactionsProcedure is the fully-qualified name of the PaymentService's
	// ListTransactions RPC.
	PaymentServiceListTransactionsProcedure = "/payment.v1.PaymentService/ListTransactions"
)

// PaymentServiceClient is a client for the payment.v1.PaymentService service.
type PaymentServiceClient interface {
	// Authorize holds funds on a payment method without capturing
	Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Capture completes a previously authorized payment
	Capture(context.Context, *connect.Request[v1.CaptureRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Sale combines authorize and capture in one operation
	Sale(context.Context, *connect.Request[v1.SaleRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Void cancels an authorized or captured payment
	Void(context.Context, *connect.Request[v1.VoidRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Refund returns funds to the customer
	Refund(context.Context, *connect.Request[v1.RefundRequest]) (*connect.Response[v1.PaymentResponse], error)
	// GetTransaction retrieves transaction details
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
	// ListTransactions lists transactions for a merchant or customer
	ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error)
}

// NewPaymentServiceClient constructs a client for the payment.v1.PaymentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paymentServiceMethods := v1.File_proto_payment_v1_payment_proto.Services().ByName("PaymentService").Methods()
	return &paymentServiceClient{
		authorize: connect.NewClient[v1.AuthorizeRequest, v1.PaymentResponse](
			httpClient,
			baseURL+PaymentServiceAuthorizeProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("Authorize")),
			connect.WithClientOptions(opts...),
		),
		capture: connect.NewClient[v1.CaptureRequest, v1.PaymentResponse](
			httpClient,
			baseURL+PaymentServiceCaptureProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("Capture")),
			connect.WithClientOptions(opts...),
		),
		sale: connect.NewClient[v1.SaleRequest, v1.PaymentResponse](
			httpClient,
			baseURL+PaymentServiceSaleProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("Sale")),
			connect.WithClientOptions(opts...),
		),
		void: connect.NewClient[v1.VoidRequest, v1.PaymentResponse](
			httpClient,
			baseURL+PaymentServiceVoidProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("Void")),
			connect.WithClientOptions(opts...),
		),
		refund: connect.NewClient[v1.RefundRequest, v1.PaymentResponse](
			httpClient,
			baseURL+PaymentServiceRefundProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("Refund")),
			connect.WithClientOptions(opts...),
		),
		getTransaction: connect.NewClient[v1.GetTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PaymentServiceGetTransactionProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("GetTransaction")),
			connect.WithClientOptions(opts...),
		),
		listTransactions: connect.NewClient[v1.ListTransactionsRequest, v1.ListTransactionsResponse](
			httpClient,
			baseURL+PaymentServiceListTransactionsProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("ListTransactions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentServiceClient implements PaymentServiceClient.
type paymentServiceClient struct {
	authorize        *connect.Client[v1.AuthorizeRequest, v1.PaymentResponse]
	capture          *connect.Client[v1.CaptureRequest, v1.PaymentResponse]
	sale             *connect.Client[v1.SaleRequest, v1.PaymentResponse]
	void             *connect.Client[v1.VoidRequest, v1.PaymentResponse]
	refund           *connect.Client[v1.RefundRequest, v1.PaymentResponse]
	getTransaction   *connect.Client[v1.GetTransactionRequest, v1.Transaction]
	listTransactions *connect.Client[v1.ListTransactionsRequest, v1.ListTransactionsResponse]
}

// Authorize calls payment.v1.PaymentService.Authorize.
func (c *paymentServiceClient) Authorize(ctx context.Context, req *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return c.authorize.CallUnary(ctx, req)
}

// Capture calls payment.v1.PaymentService.Capture.
func (c *paymentServiceClient) Capture(ctx context.Context, req *connect.Request[v1.CaptureRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return c.capture.CallUnary(ctx, req)
}

// Sale calls payment.v1.PaymentService.Sale.
func (c *paymentServiceClient) Sale(ctx context.Context, req *connect.Request[v1.SaleRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return c.sale.CallUnary(ctx, req)
}

// Void calls payment.v1.PaymentService.Void.
func (c *paymentServiceClient) Void(ctx context.Context, req *connect.Request[v1.VoidRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return c.void.CallUnary(ctx, req)
}

// Refund calls payment.v1.PaymentService.Refund.
func (c *paymentServiceClient) Refund(ctx context.Context, req *connect.Request[v1.RefundRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return c.refund.CallUnary(ctx, req)
}

// GetTransaction calls payment.v1.PaymentService.GetTransaction.
func (c *paymentServiceClient) GetTransaction(ctx context.Context, req *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.getTransaction.CallUnary(ctx, req)
}

// ListTransactions calls payment.v1.PaymentService.ListTransactions.
func (c *paymentServiceClient) ListTransactions(ctx context.Context, req *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error) {
	return c.listTransactions.CallUnary(ctx, req)
}

// PaymentServiceHandler is an implementation of the payment.v1.PaymentService service.
type PaymentServiceHandler interface {
	// Authorize holds funds on a payment method without capturing
	Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Capture completes a previously authorized payment
	Capture(context.Context, *connect.Request[v1.CaptureRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Sale combines authorize and capture in one operation
	Sale(context.Context, *connect.Request[v1.SaleRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Void cancels an authorized or captured payment
	Void(context.Context, *connect.Request[v1.VoidRequest]) (*connect.Response[v1.PaymentResponse], error)
	// Refund returns funds to the customer
	Refund(context.Context, *connect.Request[v1.RefundRequest]) (*connect.Response[v1.PaymentResponse], error)
	// GetTransaction retrieves transaction details
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
	// ListTransactions lists transactions for a merchant or customer
	ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error)
}

// NewPaymentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentServiceHandler(svc PaymentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentServiceMethods := v1.File_proto_payment_v1_payment_proto.Services().ByName("PaymentService").Methods()
	paymentServiceAuthorizeHandler := connect.NewUnaryHandler(
		PaymentServiceAuthorizeProcedure,
		svc.Authorize,
		connect.WithSchema(paymentServiceMethods.ByName("Authorize")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceCaptureHandler := connect.NewUnaryHandler(
		PaymentServiceCaptureProcedure,
		svc.Capture,
		connect.WithSchema(paymentServiceMethods.ByName("Capture")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceSaleHandler := connect.NewUnaryHandler(
		PaymentServiceSaleProcedure,
		svc.Sale,
		connect.WithSchema(paymentServiceMethods.ByName("Sale")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceVoidHandler := connect.NewUnaryHandler(
		PaymentServiceVoidProcedure,
		svc.Void,
		connect.WithSchema(paymentServiceMethods.ByName("Void")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceRefundHandler := connect.NewUnaryHandler(
		PaymentServiceRefundProcedure,
		svc.Refund,
		connect.WithSchema(paymentServiceMethods.ByName("Refund")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceGetTransactionHandler := connect.NewUnaryHandler(
		PaymentServiceGetTransactionProcedure,
		svc.GetTransaction,
		connect.WithSchema(paymentServiceMethods.ByName("GetTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceListTransactionsHandler := connect.NewUnaryHandler(
		PaymentServiceListTransactionsProcedure,
		svc.ListTransactions,
		connect.WithSchema(paymentServiceMethods.ByName("ListTransactions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/payment.v1.PaymentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentServiceAuthorizeProcedure:
			paymentServiceAuthorizeHandler.ServeHTTP(w, r)
		case PaymentServiceCaptureProcedure:
			paymentServiceCaptureHandler.ServeHTTP(w, r)
		case PaymentServiceSaleProcedure:
			paymentServiceSaleHandler.ServeHTTP(w, r)
		case PaymentServiceVoidProcedure:
			paymentServiceVoidHandler.ServeHTTP(w, r)
		case PaymentServiceRefundProcedure:
			paymentServiceRefundHandler.ServeHTTP(w, r)
		case PaymentServiceGetTransactionProcedure:
			paymentServiceGetTransactionHandler.ServeHTTP(w, r)
		case PaymentServiceListTransactionsProcedure:
			paymentServiceListTransactionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentServiceHandler struct{}

func (UnimplementedPaymentServiceHandler) Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.Authorize is not implemented"))
}

func (UnimplementedPaymentServiceHandler) Capture(context.Context, *connect.Request[v1.CaptureRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.Capture is not implemented"))
}

func (UnimplementedPaymentServiceHandler) Sale(context.Context, *connect.Request[v1.SaleRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.Sale is not implemented"))
}

func (UnimplementedPaymentServiceHandler) Void(context.Context, *connect.Request[v1.VoidRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.Void is not implemented"))
}

func (UnimplementedPaymentServiceHandler) Refund(context.Context, *connect.Request[v1.RefundRequest]) (*connect.Response[v1.PaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.Refund is not implemented"))
}

func (UnimplementedPaymentServiceHandler) GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.GetTransaction is not implemented"))
}

func (UnimplementedPaymentServiceHandler) ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.ListTransactions is not implemented"))
}
