// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAdmin = `-- name: ActivateAdmin :exec
UPDATE admins
SET is_active = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ActivateAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateAdmin, id)
	return err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (
    id, email, password_hash, role, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, password_hash, role, is_active, created_at, updated_at
`

type CreateAdminParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (
    id, admin_id, token_hash, ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, admin_id, token_hash, ip_address, user_agent, expires_at, created_at
`

type CreateAdminSessionParams struct {
	ID        uuid.UUID        `json:"id"`
	AdminID   pgtype.UUID      `json:"admin_id"`
	TokenHash string           `json:"token_hash"`
	IpAddress *netip.Addr      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.ID,
		arg.AdminID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAdmin = `-- name: DeactivateAdmin :exec
UPDATE admins
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAdmin, id)
	return err
}

const deleteAdminSession = `-- name: DeleteAdminSession :exec
DELETE FROM admin_sessions
WHERE id = $1
`

func (q *Queries) DeleteAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminSession, id)
	return err
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :exec
DELETE FROM admin_sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM admins
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM admins
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT id, admin_id, token_hash, ip_address, user_agent, expires_at, created_at FROM admin_sessions
WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) GetAdminSession(ctx context.Context, id uuid.UUID) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSession, id)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM admins
WHERE
    ($1::varchar IS NULL OR role = $1) AND
    ($2::boolean IS NULL OR is_active = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAdminsParams struct {
	Role      pgtype.Text `json:"role"`
	IsActive  pgtype.Bool `json:"is_active"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins,
		arg.Role,
		arg.IsActive,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins
SET password_hash = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateAdminPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateAdminRole = `-- name: UpdateAdminRole :exec
UPDATE admins
SET role = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateAdminRoleParams struct {
	Role pgtype.Text `json:"role"`
	ID   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminRole, arg.Role, arg.ID)
	return err
}
