// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE
    ($1::varchar IS NULL OR actor_type = $1) AND
    ($2::varchar IS NULL OR action = $2) AND
    ($3::timestamp IS NULL OR performed_at >= $3) AND
    ($4::timestamp IS NULL OR performed_at <= $4)
`

type CountAuditLogsParams struct {
	ActorType pgtype.Text      `json:"actor_type"`
	Action    pgtype.Text      `json:"action"`
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorType,
		arg.Action,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id, actor_type, actor_id, actor_name, action, entity_type, entity_id,
    changes, metadata, ip_address, user_agent, request_id, success, error_message
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14
)
`

type CreateAuditLogParams struct {
	ID           pgtype.UUID `json:"id"`
	ActorType    pgtype.Text `json:"actor_type"`
	ActorID      pgtype.Text `json:"actor_id"`
	ActorName    pgtype.Text `json:"actor_name"`
	Action       string      `json:"action"`
	EntityType   pgtype.Text `json:"entity_type"`
	EntityID     pgtype.Text `json:"entity_id"`
	Changes      []byte      `json:"changes"`
	Metadata     []byte      `json:"metadata"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	RequestID    pgtype.Text `json:"request_id"`
	Success      pgtype.Bool `json:"success"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.Success,
		arg.ErrorMessage,
	)
	return err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :execresult
DELETE FROM audit_logs
WHERE performed_at < $1
`

// Deletes audit logs older than the specified retention period
// Used by audit log retention policy to prevent unbounded growth
func (q *Queries) DeleteOldAuditLogs(ctx context.Context, cutoffDate pgtype.Timestamp) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldAuditLogs, cutoffDate)
}

const getAuditLogsByActor = `-- name: GetAuditLogsByActor :many
SELECT id, actor_type, actor_id, actor_name, action, entity_type, entity_id, changes, metadata, ip_address, user_agent, request_id, success, error_message, performed_at FROM audit_logs
WHERE actor_type = $1 AND actor_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type GetAuditLogsByActorParams struct {
	ActorType pgtype.Text `json:"actor_type"`
	ActorID   pgtype.Text `json:"actor_id"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) GetAuditLogsByActor(ctx context.Context, arg GetAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByActor, arg.ActorType, arg.ActorID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Success,
			&i.ErrorMessage,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByEntity = `-- name: GetAuditLogsByEntity :many
SELECT id, actor_type, actor_id, actor_name, action, entity_type, entity_id, changes, metadata, ip_address, user_agent, request_id, success, error_message, performed_at FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type GetAuditLogsByEntityParams struct {
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.Text `json:"entity_id"`
	LimitVal   int32       `json:"limit_val"`
}

func (q *Queries) GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByEntity, arg.EntityType, arg.EntityID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Success,
			&i.ErrorMessage,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_type, actor_id, actor_name, action, entity_type, entity_id, changes, metadata, ip_address, user_agent, request_id, success, error_message, performed_at FROM audit_logs
WHERE
    ($1::varchar IS NULL OR actor_type = $1) AND
    ($2::varchar IS NULL OR actor_id = $2) AND
    ($3::varchar IS NULL OR action = $3) AND
    ($4::varchar IS NULL OR entity_type = $4) AND
    ($5::varchar IS NULL OR entity_id = $5) AND
    ($6::timestamp IS NULL OR performed_at >= $6) AND
    ($7::timestamp IS NULL OR performed_at <= $7)
ORDER BY performed_at DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogsParams struct {
	ActorType  pgtype.Text      `json:"actor_type"`
	ActorID    pgtype.Text      `json:"actor_id"`
	Action     pgtype.Text      `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.Text      `json:"entity_id"`
	StartDate  pgtype.Timestamp `json:"start_date"`
	EndDate    pgtype.Timestamp `json:"end_date"`
	OffsetVal  int32            `json:"offset_val"`
	LimitVal   int32            `json:"limit_val"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Success,
			&i.ErrorMessage,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
