// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64       `json:"id"`
	EventType   string      `json:"event_type"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	MerchantID  string      `json:"merchant_id"`
	UserID      pgtype.Text `json:"user_id"`
	Action      string      `json:"action"`
	BeforeState []byte      `json:"before_state"`
	AfterState  []byte      `json:"after_state"`
	Metadata    []byte      `json:"metadata"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Subscription struct {
	ID                    uuid.UUID          `json:"id"`
	MerchantID            string             `json:"merchant_id"`
	CustomerID            string             `json:"customer_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Currency              string             `json:"currency"`
	Frequency             string             `json:"frequency"`
	Status                string             `json:"status"`
	PaymentMethodToken    string             `json:"payment_method_token"`
	NextBillingDate       pgtype.Date        `json:"next_billing_date"`
	FailureRetryCount     int32              `json:"failure_retry_count"`
	MaxRetries            int32              `json:"max_retries"`
	FailureOption         string             `json:"failure_option"`
	GatewaySubscriptionID pgtype.Text        `json:"gateway_subscription_id"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	CancelledAt           pgtype.Timestamptz `json:"cancelled_at"`
}

type Transaction struct {
	ID                     uuid.UUID      `json:"id"`
	MerchantID             string         `json:"merchant_id"`
	CustomerID             pgtype.Text    `json:"customer_id"`
	Amount                 pgtype.Numeric `json:"amount"`
	Currency               string         `json:"currency"`
	Status                 string         `json:"status"`
	Type                   string         `json:"type"`
	PaymentMethodType      string         `json:"payment_method_type"`
	PaymentMethodToken     pgtype.Text    `json:"payment_method_token"`
	GatewayTransactionID   pgtype.Text    `json:"gateway_transaction_id"`
	GatewayResponseCode    pgtype.Text    `json:"gateway_response_code"`
	GatewayResponseMessage pgtype.Text    `json:"gateway_response_message"`
	IdempotencyKey         pgtype.Text    `json:"idempotency_key"`
	Metadata               []byte         `json:"metadata"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}
