// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Transaction, error)
	ListActiveSubscriptionsDueForBilling(ctx context.Context, arg ListActiveSubscriptionsDueForBillingParams) ([]Subscription, error)
	ListSubscriptionsByCustomer(ctx context.Context, arg ListSubscriptionsByCustomerParams) ([]Subscription, error)
	ListTransactionsByCustomer(ctx context.Context, arg ListTransactionsByCustomerParams) ([]Transaction, error)
	ListTransactionsByMerchant(ctx context.Context, arg ListTransactionsByMerchantParams) ([]Transaction, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
}

var _ Querier = (*Queries)(nil)
