// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateAdmin(ctx context.Context, id uuid.UUID) error
	ActivateMerchant(ctx context.Context, id uuid.UUID) error
	ActivatePaymentMethod(ctx context.Context, id uuid.UUID) error
	ActivateService(ctx context.Context, id uuid.UUID) error
	AddEvidenceFile(ctx context.Context, arg AddEvidenceFileParams) error
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (Subscription, error)
	CheckServiceHasScope(ctx context.Context, arg CheckServiceHasScopeParams) (bool, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountChargebacks(ctx context.Context, arg CountChargebacksParams) (int64, error)
	CountMerchants(ctx context.Context, arg CountMerchantsParams) (int64, error)
	CountSubscriptions(ctx context.Context, arg CountSubscriptionsParams) (int64, error)
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateChargeback(ctx context.Context, arg CreateChargebackParams) (Chargeback, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (CustomerPaymentMethod, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// Transactions are append-only/immutable event logs
	// status is GENERATED column based on auth_resp, so we don't insert it
	// Uses ON CONFLICT DO NOTHING for idempotency: EPX callback retries return existing record unchanged
	// Modifications (VOID/REFUND) create NEW transaction records linked via parent_transaction_id
	// auth_guid stores EPX BRIC for this transaction (each transaction can have its own BRIC)
	// tran_nbr stores EPX TRAN_NBR (deterministic 10-digit numeric ID from UUID)
	// parent_transaction_id links to parent transaction (CAPTURE→AUTH, REFUND→SALE/CAPTURE, etc.)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error)
	DeactivateAdmin(ctx context.Context, id uuid.UUID) error
	DeactivateMerchant(ctx context.Context, id uuid.UUID) error
	DeactivatePaymentMethod(ctx context.Context, id uuid.UUID) error
	DeactivatePaymentMethodWithReason(ctx context.Context, arg DeactivatePaymentMethodWithReasonParams) error
	DeactivateService(ctx context.Context, id uuid.UUID) error
	DeleteAdminSession(ctx context.Context, id uuid.UUID) error
	DeleteExpiredAdminSessions(ctx context.Context) error
	DeletePaymentMethod(ctx context.Context, id uuid.UUID) error
	DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) error
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAdminSession(ctx context.Context, id uuid.UUID) (AdminSession, error)
	GetAuditLogsByActor(ctx context.Context, arg GetAuditLogsByActorParams) ([]AuditLog, error)
	GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]AuditLog, error)
	GetChargebackByCaseNumber(ctx context.Context, arg GetChargebackByCaseNumberParams) (Chargeback, error)
	GetChargebackByGroupID(ctx context.Context, groupID pgtype.UUID) (Chargeback, error)
	GetChargebackByID(ctx context.Context, id uuid.UUID) (Chargeback, error)
	GetDefaultPaymentMethod(ctx context.Context, arg GetDefaultPaymentMethodParams) (CustomerPaymentMethod, error)
	GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantBySlug(ctx context.Context, slug string) (Merchant, error)
	GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (CustomerPaymentMethod, error)
	// Get payment method by pre-note transaction ID (for return code processing)
	GetPaymentMethodByPreNoteTransaction(ctx context.Context, prenoteTransactionID pgtype.UUID) (CustomerPaymentMethod, error)
	// ACH Verification Management Queries
	// Get ACH payment methods pending verification older than specified cutoff date
	// Used by cron job to mark accounts as verified after 3 days with no returns
	GetPendingACHVerifications(ctx context.Context, arg GetPendingACHVerificationsParams) ([]CustomerPaymentMethod, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceByServiceID(ctx context.Context, serviceID string) (Service, error)
	GetServiceMerchantAccess(ctx context.Context, arg GetServiceMerchantAccessParams) (ServiceMerchant, error)
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	// UpdateTransaction removed: transactions are immutable/append-only
	// To modify a transaction (VOID/REFUND), create a NEW transaction record with parent_transaction_id
	GetTransactionByTranNbr(ctx context.Context, tranNbr pgtype.Text) (Transaction, error)
	// Recursively fetches a transaction and all its descendants (children, grandchildren, etc.)
	// Use this to get the full transaction tree starting from any transaction
	// Example: GetTransactionTree(auth1) returns [auth1, void1, auth2, charge2, refund2]
	// Example: GetTransactionTree(auth2) returns [auth2, charge2, refund2]
	GetTransactionTree(ctx context.Context, parentTransactionID uuid.UUID) ([]GetTransactionTreeRow, error)
	GetWebhookDeliveryHistory(ctx context.Context, arg GetWebhookDeliveryHistoryParams) ([]WebhookDelivery, error)
	GetWebhookSubscription(ctx context.Context, id uuid.UUID) (WebhookSubscription, error)
	GrantServiceAccess(ctx context.Context, arg GrantServiceAccessParams) (ServiceMerchant, error)
	// Increment ACH return count and optionally deactivate if threshold reached
	IncrementReturnCount(ctx context.Context, arg IncrementReturnCountParams) error
	IncrementSubscriptionFailureCount(ctx context.Context, arg IncrementSubscriptionFailureCountParams) (Subscription, error)
	IncrementSubscriptionRetryCount(ctx context.Context, id uuid.UUID) error
	ListActiveMerchants(ctx context.Context) ([]Merchant, error)
	ListActiveWebhooksByEvent(ctx context.Context, arg ListActiveWebhooksByEventParams) ([]WebhookSubscription, error)
	ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListChargebacks(ctx context.Context, arg ListChargebacksParams) ([]Chargeback, error)
	ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]Subscription, error)
	// Get all services that have access to a merchant
	ListMerchantServices(ctx context.Context, merchantID uuid.UUID) ([]ListMerchantServicesRow, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPaymentMethods(ctx context.Context, arg ListPaymentMethodsParams) ([]CustomerPaymentMethod, error)
	ListPaymentMethodsByCustomer(ctx context.Context, arg ListPaymentMethodsByCustomerParams) ([]CustomerPaymentMethod, error)
	ListPendingWebhookDeliveries(ctx context.Context, limitVal int32) ([]WebhookDelivery, error)
	// Get all merchants a service has access to
	ListServiceMerchants(ctx context.Context, serviceID uuid.UUID) ([]ListServiceMerchantsRow, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error)
	ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error)
	ListSubscriptionsByCustomer(ctx context.Context, arg ListSubscriptionsByCustomerParams) ([]Subscription, error)
	ListSubscriptionsDueForBilling(ctx context.Context, arg ListSubscriptionsDueForBillingParams) ([]Subscription, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListWebhookSubscriptions(ctx context.Context, arg ListWebhookSubscriptionsParams) ([]WebhookSubscription, error)
	MarkChargebackResolved(ctx context.Context, arg MarkChargebackResolvedParams) error
	// Then set the specified one as default
	MarkPaymentMethodAsDefault(ctx context.Context, id uuid.UUID) error
	MarkPaymentMethodUsed(ctx context.Context, id uuid.UUID) error
	MarkPaymentMethodVerified(ctx context.Context, id uuid.UUID) error
	// Mark ACH verification as failed and deactivate payment method
	MarkVerificationFailed(ctx context.Context, arg MarkVerificationFailedParams) error
	MerchantExists(ctx context.Context, id uuid.UUID) (bool, error)
	MerchantExistsBySlug(ctx context.Context, slug string) (bool, error)
	ResetSubscriptionRetryCount(ctx context.Context, id uuid.UUID) error
	RevokeServiceAccess(ctx context.Context, arg RevokeServiceAccessParams) error
	RotateServiceKey(ctx context.Context, arg RotateServiceKeyParams) (Service, error)
	// First unset all defaults for this customer
	SetPaymentMethodAsDefault(ctx context.Context, arg SetPaymentMethodAsDefaultParams) error
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error
	UpdateChargeback(ctx context.Context, arg UpdateChargebackParams) (Chargeback, error)
	UpdateChargebackNotes(ctx context.Context, arg UpdateChargebackNotesParams) error
	UpdateChargebackResponse(ctx context.Context, arg UpdateChargebackResponseParams) error
	UpdateChargebackStatus(ctx context.Context, arg UpdateChargebackStatusParams) (Chargeback, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
	UpdateMerchantMACPath(ctx context.Context, arg UpdateMerchantMACPathParams) error
	UpdateNextBillingDate(ctx context.Context, arg UpdateNextBillingDateParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceScopes(ctx context.Context, arg UpdateServiceScopesParams) (ServiceMerchant, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateSubscriptionBilling(ctx context.Context, arg UpdateSubscriptionBillingParams) (Subscription, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	// Updates transaction with EPX response data (for Browser Post callback)
	// Only updates EPX response fields, leaves core transaction data unchanged
	UpdateTransactionFromEPXResponse(ctx context.Context, arg UpdateTransactionFromEPXResponseParams) (Transaction, error)
	// Update verification status and related fields
	UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) error
	UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) (WebhookDelivery, error)
	UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error)
}

var _ Querier = (*Queries)(nil)
