// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: api/proto/subscription/v1/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BillingFrequency defines how often to bill
type BillingFrequency int32

const (
	BillingFrequency_BILLING_FREQUENCY_UNSPECIFIED BillingFrequency = 0
	BillingFrequency_BILLING_FREQUENCY_WEEKLY      BillingFrequency = 1
	BillingFrequency_BILLING_FREQUENCY_BIWEEKLY    BillingFrequency = 2
	BillingFrequency_BILLING_FREQUENCY_MONTHLY     BillingFrequency = 3
	BillingFrequency_BILLING_FREQUENCY_YEARLY      BillingFrequency = 4
)

// Enum value maps for BillingFrequency.
var (
	BillingFrequency_name = map[int32]string{
		0: "BILLING_FREQUENCY_UNSPECIFIED",
		1: "BILLING_FREQUENCY_WEEKLY",
		2: "BILLING_FREQUENCY_BIWEEKLY",
		3: "BILLING_FREQUENCY_MONTHLY",
		4: "BILLING_FREQUENCY_YEARLY",
	}
	BillingFrequency_value = map[string]int32{
		"BILLING_FREQUENCY_UNSPECIFIED": 0,
		"BILLING_FREQUENCY_WEEKLY":      1,
		"BILLING_FREQUENCY_BIWEEKLY":    2,
		"BILLING_FREQUENCY_MONTHLY":     3,
		"BILLING_FREQUENCY_YEARLY":      4,
	}
)

func (x BillingFrequency) Enum() *BillingFrequency {
	p := new(BillingFrequency)
	*p = x
	return p
}

func (x BillingFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillingFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_subscription_v1_subscription_proto_enumTypes[0].Descriptor()
}

func (BillingFrequency) Type() protoreflect.EnumType {
	return &file_api_proto_subscription_v1_subscription_proto_enumTypes[0]
}

func (x BillingFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillingFrequency.Descriptor instead.
func (BillingFrequency) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

// SubscriptionStatus represents the subscription state
type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE      SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAUSED      SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED   SubscriptionStatus = 3
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAST_DUE    SubscriptionStatus = 4
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_ACTIVE",
		2: "SUBSCRIPTION_STATUS_PAUSED",
		3: "SUBSCRIPTION_STATUS_CANCELLED",
		4: "SUBSCRIPTION_STATUS_PAST_DUE",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_ACTIVE":      1,
		"SUBSCRIPTION_STATUS_PAUSED":      2,
		"SUBSCRIPTION_STATUS_CANCELLED":   3,
		"SUBSCRIPTION_STATUS_PAST_DUE":    4,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_subscription_v1_subscription_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_subscription_v1_subscription_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

// FailureOption defines what to do when billing fails
type FailureOption int32

const (
	FailureOption_FAILURE_OPTION_UNSPECIFIED FailureOption = 0
	FailureOption_FAILURE_OPTION_FORWARD     FailureOption = 1 // Reschedule to next period
	FailureOption_FAILURE_OPTION_SKIP        FailureOption = 2 // Skip this period
	FailureOption_FAILURE_OPTION_PAUSE       FailureOption = 3 // Pause subscription
)

// Enum value maps for FailureOption.
var (
	FailureOption_name = map[int32]string{
		0: "FAILURE_OPTION_UNSPECIFIED",
		1: "FAILURE_OPTION_FORWARD",
		2: "FAILURE_OPTION_SKIP",
		3: "FAILURE_OPTION_PAUSE",
	}
	FailureOption_value = map[string]int32{
		"FAILURE_OPTION_UNSPECIFIED": 0,
		"FAILURE_OPTION_FORWARD":     1,
		"FAILURE_OPTION_SKIP":        2,
		"FAILURE_OPTION_PAUSE":       3,
	}
)

func (x FailureOption) Enum() *FailureOption {
	p := new(FailureOption)
	*p = x
	return p
}

func (x FailureOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureOption) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_subscription_v1_subscription_proto_enumTypes[2].Descriptor()
}

func (FailureOption) Type() protoreflect.EnumType {
	return &file_api_proto_subscription_v1_subscription_proto_enumTypes[2]
}

func (x FailureOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureOption.Descriptor instead.
func (FailureOption) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

// CreateSubscriptionRequest creates a new subscription
type CreateSubscriptionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MerchantId         string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId         string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount             string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Decimal as string
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Frequency          BillingFrequency       `protobuf:"varint,5,opt,name=frequency,proto3,enum=subscription.v1.BillingFrequency" json:"frequency,omitempty"`
	PaymentMethodToken string                 `protobuf:"bytes,6,opt,name=payment_method_token,json=paymentMethodToken,proto3" json:"payment_method_token,omitempty"` // BRIC token for recurring charges
	StartDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	MaxRetries         int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"` // Default: 3
	FailureOption      FailureOption          `protobuf:"varint,9,opt,name=failure_option,json=failureOption,proto3,enum=subscription.v1.FailureOption" json:"failure_option,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdempotencyKey     string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetFrequency() BillingFrequency {
	if x != nil {
		return x.Frequency
	}
	return BillingFrequency_BILLING_FREQUENCY_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetPaymentMethodToken() string {
	if x != nil {
		return x.PaymentMethodToken
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetFailureOption() FailureOption {
	if x != nil {
		return x.FailureOption
	}
	return FailureOption_FAILURE_OPTION_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// UpdateSubscriptionRequest updates subscription properties
type UpdateSubscriptionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId     string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Amount             *string                `protobuf:"bytes,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`                                                     // Optional: update amount
	Frequency          *BillingFrequency      `protobuf:"varint,3,opt,name=frequency,proto3,enum=subscription.v1.BillingFrequency,oneof" json:"frequency,omitempty"`        // Optional: update frequency
	PaymentMethodToken *string                `protobuf:"bytes,4,opt,name=payment_method_token,json=paymentMethodToken,proto3,oneof" json:"payment_method_token,omitempty"` // Optional: update payment method
	IdempotencyKey     string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetFrequency() BillingFrequency {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return BillingFrequency_BILLING_FREQUENCY_UNSPECIFIED
}

func (x *UpdateSubscriptionRequest) GetPaymentMethodToken() string {
	if x != nil && x.PaymentMethodToken != nil {
		return *x.PaymentMethodToken
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// CancelSubscriptionRequest cancels a subscription
type CancelSubscriptionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId    string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	CancelAtPeriodEnd bool                   `protobuf:"varint,2,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"` // If true, cancel after current billing period
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// PauseSubscriptionRequest pauses a subscription
type PauseSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PauseSubscriptionRequest) Reset() {
	*x = PauseSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSubscriptionRequest) ProtoMessage() {}

func (x *PauseSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*PauseSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *PauseSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// ResumeSubscriptionRequest resumes a subscription
type ResumeSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeSubscriptionRequest) Reset() {
	*x = ResumeSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSubscriptionRequest) ProtoMessage() {}

func (x *ResumeSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ResumeSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetSubscriptionRequest retrieves a subscription
type GetSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// ListCustomerSubscriptionsRequest lists customer subscriptions
type ListCustomerSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerSubscriptionsRequest) Reset() {
	*x = ListCustomerSubscriptionsRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerSubscriptionsRequest) ProtoMessage() {}

func (x *ListCustomerSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *ListCustomerSubscriptionsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListCustomerSubscriptionsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// ListCustomerSubscriptionsResponse contains subscription list
type ListCustomerSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerSubscriptionsResponse) Reset() {
	*x = ListCustomerSubscriptionsResponse{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerSubscriptionsResponse) ProtoMessage() {}

func (x *ListCustomerSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ListCustomerSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// ProcessDueBillingRequest processes billing batch
type ProcessDueBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsOfDate      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=as_of_date,json=asOfDate,proto3" json:"as_of_date,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"` // Default: 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDueBillingRequest) Reset() {
	*x = ProcessDueBillingRequest{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDueBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDueBillingRequest) ProtoMessage() {}

func (x *ProcessDueBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDueBillingRequest.ProtoReflect.Descriptor instead.
func (*ProcessDueBillingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessDueBillingRequest) GetAsOfDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOfDate
	}
	return nil
}

func (x *ProcessDueBillingRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ProcessDueBillingResponse contains billing results
type ProcessDueBillingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount int32                  `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	SuccessCount   int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount    int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	SkippedCount   int32                  `protobuf:"varint,4,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	Errors         []*BillingError        `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessDueBillingResponse) Reset() {
	*x = ProcessDueBillingResponse{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDueBillingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDueBillingResponse) ProtoMessage() {}

func (x *ProcessDueBillingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDueBillingResponse.ProtoReflect.Descriptor instead.
func (*ProcessDueBillingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessDueBillingResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *ProcessDueBillingResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ProcessDueBillingResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *ProcessDueBillingResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *ProcessDueBillingResponse) GetErrors() []*BillingError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// BillingError represents a billing failure
type BillingError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Retriable      bool                   `protobuf:"varint,4,opt,name=retriable,proto3" json:"retriable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BillingError) Reset() {
	*x = BillingError{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingError) ProtoMessage() {}

func (x *BillingError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingError.ProtoReflect.Descriptor instead.
func (*BillingError) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *BillingError) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *BillingError) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *BillingError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BillingError) GetRetriable() bool {
	if x != nil {
		return x.Retriable
	}
	return false
}

// SubscriptionResponse is returned from subscription operations
type SubscriptionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId        string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	MerchantId            string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId            string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount                string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Frequency             BillingFrequency       `protobuf:"varint,6,opt,name=frequency,proto3,enum=subscription.v1.BillingFrequency" json:"frequency,omitempty"`
	Status                SubscriptionStatus     `protobuf:"varint,7,opt,name=status,proto3,enum=subscription.v1.SubscriptionStatus" json:"status,omitempty"`
	PaymentMethodToken    string                 `protobuf:"bytes,8,opt,name=payment_method_token,json=paymentMethodToken,proto3" json:"payment_method_token,omitempty"`
	NextBillingDate       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=next_billing_date,json=nextBillingDate,proto3" json:"next_billing_date,omitempty"`
	GatewaySubscriptionId string                 `protobuf:"bytes,10,opt,name=gateway_subscription_id,json=gatewaySubscriptionId,proto3" json:"gateway_subscription_id,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CancelledAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=cancelled_at,json=cancelledAt,proto3,oneof" json:"cancelled_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *SubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SubscriptionResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SubscriptionResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SubscriptionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubscriptionResponse) GetFrequency() BillingFrequency {
	if x != nil {
		return x.Frequency
	}
	return BillingFrequency_BILLING_FREQUENCY_UNSPECIFIED
}

func (x *SubscriptionResponse) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *SubscriptionResponse) GetPaymentMethodToken() string {
	if x != nil {
		return x.PaymentMethodToken
	}
	return ""
}

func (x *SubscriptionResponse) GetNextBillingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextBillingDate
	}
	return nil
}

func (x *SubscriptionResponse) GetGatewaySubscriptionId() string {
	if x != nil {
		return x.GatewaySubscriptionId
	}
	return ""
}

func (x *SubscriptionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubscriptionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SubscriptionResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

// Subscription represents a complete subscription record
type Subscription struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId            string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CustomerId            string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount                string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Frequency             BillingFrequency       `protobuf:"varint,6,opt,name=frequency,proto3,enum=subscription.v1.BillingFrequency" json:"frequency,omitempty"`
	Status                SubscriptionStatus     `protobuf:"varint,7,opt,name=status,proto3,enum=subscription.v1.SubscriptionStatus" json:"status,omitempty"`
	PaymentMethodToken    string                 `protobuf:"bytes,8,opt,name=payment_method_token,json=paymentMethodToken,proto3" json:"payment_method_token,omitempty"`
	NextBillingDate       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=next_billing_date,json=nextBillingDate,proto3" json:"next_billing_date,omitempty"`
	GatewaySubscriptionId string                 `protobuf:"bytes,10,opt,name=gateway_subscription_id,json=gatewaySubscriptionId,proto3" json:"gateway_subscription_id,omitempty"`
	FailureRetryCount     int32                  `protobuf:"varint,11,opt,name=failure_retry_count,json=failureRetryCount,proto3" json:"failure_retry_count,omitempty"`
	MaxRetries            int32                  `protobuf:"varint,12,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	FailureOption         FailureOption          `protobuf:"varint,13,opt,name=failure_option,json=failureOption,proto3,enum=subscription.v1.FailureOption" json:"failure_option,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CancelledAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=cancelled_at,json=cancelledAt,proto3,oneof" json:"cancelled_at,omitempty"`
	Metadata              map[string]string      `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_v1_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Subscription) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Subscription) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Subscription) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Subscription) GetFrequency() BillingFrequency {
	if x != nil {
		return x.Frequency
	}
	return BillingFrequency_BILLING_FREQUENCY_UNSPECIFIED
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetPaymentMethodToken() string {
	if x != nil {
		return x.PaymentMethodToken
	}
	return ""
}

func (x *Subscription) GetNextBillingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextBillingDate
	}
	return nil
}

func (x *Subscription) GetGatewaySubscriptionId() string {
	if x != nil {
		return x.GatewaySubscriptionId
	}
	return ""
}

func (x *Subscription) GetFailureRetryCount() int32 {
	if x != nil {
		return x.FailureRetryCount
	}
	return 0
}

func (x *Subscription) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Subscription) GetFailureOption() FailureOption {
	if x != nil {
		return x.FailureOption
	}
	return FailureOption_FAILURE_OPTION_UNSPECIFIED
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Subscription) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Subscription) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_api_proto_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	",api/proto/subscription/v1/subscription.proto\x12\x0fsubscription.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x04\n" +
	"\x19CreateSubscriptionRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12?\n" +
	"\tfrequency\x18\x05 \x01(\x0e2!.subscription.v1.BillingFrequencyR\tfrequency\x120\n" +
	"\x14payment_method_token\x18\x06 \x01(\tR\x12paymentMethodToken\x129\n" +
	"\n" +
	"start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12E\n" +
	"\x0efailure_option\x18\t \x01(\x0e2\x1e.subscription.v1.FailureOptionR\rfailureOption\x12T\n" +
	"\bmetadata\x18\n" +
	" \x03(\v28.subscription.v1.CreateSubscriptionRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x02\n" +
	"\x19UpdateSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\tH\x00R\x06amount\x88\x01\x01\x12D\n" +
	"\tfrequency\x18\x03 \x01(\x0e2!.subscription.v1.BillingFrequencyH\x01R\tfrequency\x88\x01\x01\x125\n" +
	"\x14payment_method_token\x18\x04 \x01(\tH\x02R\x12paymentMethodToken\x88\x01\x01\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKeyB\t\n" +
	"\a_amountB\f\n" +
	"\n" +
	"_frequencyB\x17\n" +
	"\x15_payment_method_token\"\xb6\x01\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12/\n" +
	"\x14cancel_at_period_end\x18\x02 \x01(\bR\x11cancelAtPeriodEnd\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"C\n" +
	"\x18PauseSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"D\n" +
	"\x19ResumeSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"A\n" +
	"\x16GetSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"d\n" +
	" ListCustomerSubscriptionsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"h\n" +
	"!ListCustomerSubscriptionsResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.subscription.v1.SubscriptionR\rsubscriptions\"s\n" +
	"\x18ProcessDueBillingRequest\x128\n" +
	"\n" +
	"as_of_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\basOfDate\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\"\xe8\x01\n" +
	"\x19ProcessDueBillingResponse\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x05R\x0eprocessedCount\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12#\n" +
	"\rskipped_count\x18\x04 \x01(\x05R\fskippedCount\x125\n" +
	"\x06errors\x18\x05 \x03(\v2\x1d.subscription.v1.BillingErrorR\x06errors\"\x8c\x01\n" +
	"\fBillingError\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1c\n" +
	"\tretriable\x18\x04 \x01(\bR\tretriable\"\xb0\x05\n" +
	"\x14SubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12?\n" +
	"\tfrequency\x18\x06 \x01(\x0e2!.subscription.v1.BillingFrequencyR\tfrequency\x12;\n" +
	"\x06status\x18\a \x01(\x0e2#.subscription.v1.SubscriptionStatusR\x06status\x120\n" +
	"\x14payment_method_token\x18\b \x01(\tR\x12paymentMethodToken\x12F\n" +
	"\x11next_billing_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fnextBillingDate\x126\n" +
	"\x17gateway_subscription_id\x18\n" +
	" \x01(\tR\x15gatewaySubscriptionId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fcancelled_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcancelledAt\x88\x01\x01B\x0f\n" +
	"\r_cancelled_at\"\xad\a\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12?\n" +
	"\tfrequency\x18\x06 \x01(\x0e2!.subscription.v1.BillingFrequencyR\tfrequency\x12;\n" +
	"\x06status\x18\a \x01(\x0e2#.subscription.v1.SubscriptionStatusR\x06status\x120\n" +
	"\x14payment_method_token\x18\b \x01(\tR\x12paymentMethodToken\x12F\n" +
	"\x11next_billing_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fnextBillingDate\x126\n" +
	"\x17gateway_subscription_id\x18\n" +
	" \x01(\tR\x15gatewaySubscriptionId\x12.\n" +
	"\x13failure_retry_count\x18\v \x01(\x05R\x11failureRetryCount\x12\x1f\n" +
	"\vmax_retries\x18\f \x01(\x05R\n" +
	"maxRetries\x12E\n" +
	"\x0efailure_option\x18\r \x01(\x0e2\x1e.subscription.v1.FailureOptionR\rfailureOption\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fcancelled_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcancelledAt\x88\x01\x01\x12G\n" +
	"\bmetadata\x18\x11 \x03(\v2+.subscription.v1.Subscription.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_cancelled_at*\xb0\x01\n" +
	"\x10BillingFrequency\x12!\n" +
	"\x1dBILLING_FREQUENCY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BILLING_FREQUENCY_WEEKLY\x10\x01\x12\x1e\n" +
	"\x1aBILLING_FREQUENCY_BIWEEKLY\x10\x02\x12\x1d\n" +
	"\x19BILLING_FREQUENCY_MONTHLY\x10\x03\x12\x1c\n" +
	"\x18BILLING_FREQUENCY_YEARLY\x10\x04*\xbe\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x01\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_PAUSED\x10\x02\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x03\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_PAST_DUE\x10\x04*~\n" +
	"\rFailureOption\x12\x1e\n" +
	"\x1aFAILURE_OPTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FAILURE_OPTION_FORWARD\x10\x01\x12\x17\n" +
	"\x13FAILURE_OPTION_SKIP\x10\x02\x12\x18\n" +
	"\x14FAILURE_OPTION_PAUSE\x10\x032\xec\x06\n" +
	"\x13SubscriptionService\x12g\n" +
	"\x12CreateSubscription\x12*.subscription.v1.CreateSubscriptionRequest\x1a%.subscription.v1.SubscriptionResponse\x12g\n" +
	"\x12UpdateSubscription\x12*.subscription.v1.UpdateSubscriptionRequest\x1a%.subscription.v1.SubscriptionResponse\x12g\n" +
	"\x12CancelSubscription\x12*.subscription.v1.CancelSubscriptionRequest\x1a%.subscription.v1.SubscriptionResponse\x12e\n" +
	"\x11PauseSubscription\x12).subscription.v1.PauseSubscriptionRequest\x1a%.subscription.v1.SubscriptionResponse\x12g\n" +
	"\x12ResumeSubscription\x12*.subscription.v1.ResumeSubscriptionRequest\x1a%.subscription.v1.SubscriptionResponse\x12Y\n" +
	"\x0fGetSubscription\x12'.subscription.v1.GetSubscriptionRequest\x1a\x1d.subscription.v1.Subscription\x12\x82\x01\n" +
	"\x19ListCustomerSubscriptions\x121.subscription.v1.ListCustomerSubscriptionsRequest\x1a2.subscription.v1.ListCustomerSubscriptionsResponse\x12j\n" +
	"\x11ProcessDueBilling\x12).subscription.v1.ProcessDueBillingRequest\x1a*.subscription.v1.ProcessDueBillingResponseBPZNgithub.com/kevin07696/payment-service/api/proto/subscription/v1;subscriptionv1b\x06proto3"

var (
	file_api_proto_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_api_proto_subscription_v1_subscription_proto_rawDescData []byte
)

func file_api_proto_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_api_proto_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_api_proto_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscription_v1_subscription_proto_rawDesc), len(file_api_proto_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_api_proto_subscription_v1_subscription_proto_rawDescData
}

var file_api_proto_subscription_v1_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_subscription_v1_subscription_proto_goTypes = []any{
	(BillingFrequency)(0),                     // 0: subscription.v1.BillingFrequency
	(SubscriptionStatus)(0),                   // 1: subscription.v1.SubscriptionStatus
	(FailureOption)(0),                        // 2: subscription.v1.FailureOption
	(*CreateSubscriptionRequest)(nil),         // 3: subscription.v1.CreateSubscriptionRequest
	(*UpdateSubscriptionRequest)(nil),         // 4: subscription.v1.UpdateSubscriptionRequest
	(*CancelSubscriptionRequest)(nil),         // 5: subscription.v1.CancelSubscriptionRequest
	(*PauseSubscriptionRequest)(nil),          // 6: subscription.v1.PauseSubscriptionRequest
	(*ResumeSubscriptionRequest)(nil),         // 7: subscription.v1.ResumeSubscriptionRequest
	(*GetSubscriptionRequest)(nil),            // 8: subscription.v1.GetSubscriptionRequest
	(*ListCustomerSubscriptionsRequest)(nil),  // 9: subscription.v1.ListCustomerSubscriptionsRequest
	(*ListCustomerSubscriptionsResponse)(nil), // 10: subscription.v1.ListCustomerSubscriptionsResponse
	(*ProcessDueBillingRequest)(nil),          // 11: subscription.v1.ProcessDueBillingRequest
	(*ProcessDueBillingResponse)(nil),         // 12: subscription.v1.ProcessDueBillingResponse
	(*BillingError)(nil),                      // 13: subscription.v1.BillingError
	(*SubscriptionResponse)(nil),              // 14: subscription.v1.SubscriptionResponse
	(*Subscription)(nil),                      // 15: subscription.v1.Subscription
	nil,                                       // 16: subscription.v1.CreateSubscriptionRequest.MetadataEntry
	nil,                                       // 17: subscription.v1.Subscription.MetadataEntry
	(*timestamppb.Timestamp)(nil),             // 18: google.protobuf.Timestamp
}
var file_api_proto_subscription_v1_subscription_proto_depIdxs = []int32{
	0,  // 0: subscription.v1.CreateSubscriptionRequest.frequency:type_name -> subscription.v1.BillingFrequency
	18, // 1: subscription.v1.CreateSubscriptionRequest.start_date:type_name -> google.protobuf.Timestamp
	2,  // 2: subscription.v1.CreateSubscriptionRequest.failure_option:type_name -> subscription.v1.FailureOption
	16, // 3: subscription.v1.CreateSubscriptionRequest.metadata:type_name -> subscription.v1.CreateSubscriptionRequest.MetadataEntry
	0,  // 4: subscription.v1.UpdateSubscriptionRequest.frequency:type_name -> subscription.v1.BillingFrequency
	15, // 5: subscription.v1.ListCustomerSubscriptionsResponse.subscriptions:type_name -> subscription.v1.Subscription
	18, // 6: subscription.v1.ProcessDueBillingRequest.as_of_date:type_name -> google.protobuf.Timestamp
	13, // 7: subscription.v1.ProcessDueBillingResponse.errors:type_name -> subscription.v1.BillingError
	0,  // 8: subscription.v1.SubscriptionResponse.frequency:type_name -> subscription.v1.BillingFrequency
	1,  // 9: subscription.v1.SubscriptionResponse.status:type_name -> subscription.v1.SubscriptionStatus
	18, // 10: subscription.v1.SubscriptionResponse.next_billing_date:type_name -> google.protobuf.Timestamp
	18, // 11: subscription.v1.SubscriptionResponse.created_at:type_name -> google.protobuf.Timestamp
	18, // 12: subscription.v1.SubscriptionResponse.updated_at:type_name -> google.protobuf.Timestamp
	18, // 13: subscription.v1.SubscriptionResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	0,  // 14: subscription.v1.Subscription.frequency:type_name -> subscription.v1.BillingFrequency
	1,  // 15: subscription.v1.Subscription.status:type_name -> subscription.v1.SubscriptionStatus
	18, // 16: subscription.v1.Subscription.next_billing_date:type_name -> google.protobuf.Timestamp
	2,  // 17: subscription.v1.Subscription.failure_option:type_name -> subscription.v1.FailureOption
	18, // 18: subscription.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	18, // 19: subscription.v1.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	18, // 20: subscription.v1.Subscription.cancelled_at:type_name -> google.protobuf.Timestamp
	17, // 21: subscription.v1.Subscription.metadata:type_name -> subscription.v1.Subscription.MetadataEntry
	3,  // 22: subscription.v1.SubscriptionService.CreateSubscription:input_type -> subscription.v1.CreateSubscriptionRequest
	4,  // 23: subscription.v1.SubscriptionService.UpdateSubscription:input_type -> subscription.v1.UpdateSubscriptionRequest
	5,  // 24: subscription.v1.SubscriptionService.CancelSubscription:input_type -> subscription.v1.CancelSubscriptionRequest
	6,  // 25: subscription.v1.SubscriptionService.PauseSubscription:input_type -> subscription.v1.PauseSubscriptionRequest
	7,  // 26: subscription.v1.SubscriptionService.ResumeSubscription:input_type -> subscription.v1.ResumeSubscriptionRequest
	8,  // 27: subscription.v1.SubscriptionService.GetSubscription:input_type -> subscription.v1.GetSubscriptionRequest
	9,  // 28: subscription.v1.SubscriptionService.ListCustomerSubscriptions:input_type -> subscription.v1.ListCustomerSubscriptionsRequest
	11, // 29: subscription.v1.SubscriptionService.ProcessDueBilling:input_type -> subscription.v1.ProcessDueBillingRequest
	14, // 30: subscription.v1.SubscriptionService.CreateSubscription:output_type -> subscription.v1.SubscriptionResponse
	14, // 31: subscription.v1.SubscriptionService.UpdateSubscription:output_type -> subscription.v1.SubscriptionResponse
	14, // 32: subscription.v1.SubscriptionService.CancelSubscription:output_type -> subscription.v1.SubscriptionResponse
	14, // 33: subscription.v1.SubscriptionService.PauseSubscription:output_type -> subscription.v1.SubscriptionResponse
	14, // 34: subscription.v1.SubscriptionService.ResumeSubscription:output_type -> subscription.v1.SubscriptionResponse
	15, // 35: subscription.v1.SubscriptionService.GetSubscription:output_type -> subscription.v1.Subscription
	10, // 36: subscription.v1.SubscriptionService.ListCustomerSubscriptions:output_type -> subscription.v1.ListCustomerSubscriptionsResponse
	12, // 37: subscription.v1.SubscriptionService.ProcessDueBilling:output_type -> subscription.v1.ProcessDueBillingResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_subscription_v1_subscription_proto_init() }
func file_api_proto_subscription_v1_subscription_proto_init() {
	if File_api_proto_subscription_v1_subscription_proto != nil {
		return
	}
	file_api_proto_subscription_v1_subscription_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_subscription_v1_subscription_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_proto_subscription_v1_subscription_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscription_v1_subscription_proto_rawDesc), len(file_api_proto_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_api_proto_subscription_v1_subscription_proto_depIdxs,
		EnumInfos:         file_api_proto_subscription_v1_subscription_proto_enumTypes,
		MessageInfos:      file_api_proto_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_api_proto_subscription_v1_subscription_proto = out.File
	file_api_proto_subscription_v1_subscription_proto_goTypes = nil
	file_api_proto_subscription_v1_subscription_proto_depIdxs = nil
}
