// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/chargeback/v1/chargeback.proto

package chargebackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChargebackStatus represents the chargeback state
// Matches database constraint: ('new', 'pending', 'responded', 'won', 'lost', 'accepted')
type ChargebackStatus int32

const (
	ChargebackStatus_CHARGEBACK_STATUS_UNSPECIFIED ChargebackStatus = 0
	ChargebackStatus_CHARGEBACK_STATUS_NEW         ChargebackStatus = 1
	ChargebackStatus_CHARGEBACK_STATUS_PENDING     ChargebackStatus = 2
	ChargebackStatus_CHARGEBACK_STATUS_RESPONDED   ChargebackStatus = 3
	ChargebackStatus_CHARGEBACK_STATUS_WON         ChargebackStatus = 4
	ChargebackStatus_CHARGEBACK_STATUS_LOST        ChargebackStatus = 5
	ChargebackStatus_CHARGEBACK_STATUS_ACCEPTED    ChargebackStatus = 6
)

// Enum value maps for ChargebackStatus.
var (
	ChargebackStatus_name = map[int32]string{
		0: "CHARGEBACK_STATUS_UNSPECIFIED",
		1: "CHARGEBACK_STATUS_NEW",
		2: "CHARGEBACK_STATUS_PENDING",
		3: "CHARGEBACK_STATUS_RESPONDED",
		4: "CHARGEBACK_STATUS_WON",
		5: "CHARGEBACK_STATUS_LOST",
		6: "CHARGEBACK_STATUS_ACCEPTED",
	}
	ChargebackStatus_value = map[string]int32{
		"CHARGEBACK_STATUS_UNSPECIFIED": 0,
		"CHARGEBACK_STATUS_NEW":         1,
		"CHARGEBACK_STATUS_PENDING":     2,
		"CHARGEBACK_STATUS_RESPONDED":   3,
		"CHARGEBACK_STATUS_WON":         4,
		"CHARGEBACK_STATUS_LOST":        5,
		"CHARGEBACK_STATUS_ACCEPTED":    6,
	}
)

func (x ChargebackStatus) Enum() *ChargebackStatus {
	p := new(ChargebackStatus)
	*p = x
	return p
}

func (x ChargebackStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargebackStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chargeback_v1_chargeback_proto_enumTypes[0].Descriptor()
}

func (ChargebackStatus) Type() protoreflect.EnumType {
	return &file_proto_chargeback_v1_chargeback_proto_enumTypes[0]
}

func (x ChargebackStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargebackStatus.Descriptor instead.
func (ChargebackStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_chargeback_v1_chargeback_proto_rawDescGZIP(), []int{0}
}

// GetChargebackRequest retrieves a chargeback by ID
type GetChargebackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargebackId  string                 `protobuf:"bytes,1,opt,name=chargeback_id,json=chargebackId,proto3" json:"chargeback_id,omitempty"` // UUID
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChargebackRequest) Reset() {
	*x = GetChargebackRequest{}
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargebackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargebackRequest) ProtoMessage() {}

func (x *GetChargebackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargebackRequest.ProtoReflect.Descriptor instead.
func (*GetChargebackRequest) Descriptor() ([]byte, []int) {
	return file_proto_chargeback_v1_chargeback_proto_rawDescGZIP(), []int{0}
}

func (x *GetChargebackRequest) GetChargebackId() string {
	if x != nil {
		return x.ChargebackId
	}
	return ""
}

func (x *GetChargebackRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// ListChargebacksRequest lists chargebacks with flexible filters
type ListChargebacksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                 // Required: merchant/agent ID
	CustomerId      *string                `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3,oneof" json:"customer_id,omitempty"`                  // Optional: filter by customer
	GroupId         *string                `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`                           // Optional: filter by transaction group
	Status          *ChargebackStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=chargeback.v1.ChargebackStatus,oneof" json:"status,omitempty"`       // Optional: filter by status
	DisputeDateFrom *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dispute_date_from,json=disputeDateFrom,proto3,oneof" json:"dispute_date_from,omitempty"` // Optional: date range
	DisputeDateTo   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=dispute_date_to,json=disputeDateTo,proto3,oneof" json:"dispute_date_to,omitempty"`
	Limit           int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"` // Default: 100
	Offset          int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListChargebacksRequest) Reset() {
	*x = ListChargebacksRequest{}
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChargebacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChargebacksRequest) ProtoMessage() {}

func (x *ListChargebacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChargebacksRequest.ProtoReflect.Descriptor instead.
func (*ListChargebacksRequest) Descriptor() ([]byte, []int) {
	return file_proto_chargeback_v1_chargeback_proto_rawDescGZIP(), []int{1}
}

func (x *ListChargebacksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListChargebacksRequest) GetCustomerId() string {
	if x != nil && x.CustomerId != nil {
		return *x.CustomerId
	}
	return ""
}

func (x *ListChargebacksRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *ListChargebacksRequest) GetStatus() ChargebackStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ChargebackStatus_CHARGEBACK_STATUS_UNSPECIFIED
}

func (x *ListChargebacksRequest) GetDisputeDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DisputeDateFrom
	}
	return nil
}

func (x *ListChargebacksRequest) GetDisputeDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DisputeDateTo
	}
	return nil
}

func (x *ListChargebacksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChargebacksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListChargebacksResponse contains chargeback list
type ListChargebacksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chargebacks   []*Chargeback          `protobuf:"bytes,1,rep,name=chargebacks,proto3" json:"chargebacks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChargebacksResponse) Reset() {
	*x = ListChargebacksResponse{}
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChargebacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChargebacksResponse) ProtoMessage() {}

func (x *ListChargebacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChargebacksResponse.ProtoReflect.Descriptor instead.
func (*ListChargebacksResponse) Descriptor() ([]byte, []int) {
	return file_proto_chargeback_v1_chargeback_proto_rawDescGZIP(), []int{2}
}

func (x *ListChargebacksResponse) GetChargebacks() []*Chargeback {
	if x != nil {
		return x.Chargebacks
	}
	return nil
}

func (x *ListChargebacksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Chargeback represents a complete chargeback record (read-only)
type Chargeback struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId    string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // Links to transaction group
	AgentId    string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// North API fields
	CaseNumber        string                 `protobuf:"bytes,5,opt,name=case_number,json=caseNumber,proto3" json:"case_number,omitempty"` // North's caseNumber
	DisputeDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=dispute_date,json=disputeDate,proto3" json:"dispute_date,omitempty"`
	ChargebackDate    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=chargeback_date,json=chargebackDate,proto3" json:"chargeback_date,omitempty"`
	ChargebackAmount  string                 `protobuf:"bytes,8,opt,name=chargeback_amount,json=chargebackAmount,proto3" json:"chargeback_amount,omitempty"` // Decimal as string
	Currency          string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	ReasonCode        string                 `protobuf:"bytes,10,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`                      // North's reasonCode (e.g., "P22", "F10")
	ReasonDescription string                 `protobuf:"bytes,11,opt,name=reason_description,json=reasonDescription,proto3" json:"reason_description,omitempty"` // North's reasonDescription
	// Status and timeline
	Status              ChargebackStatus       `protobuf:"varint,12,opt,name=status,proto3,enum=chargeback.v1.ChargebackStatus" json:"status,omitempty"`
	RespondByDate       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=respond_by_date,json=respondByDate,proto3,oneof" json:"respond_by_date,omitempty"`
	ResponseSubmittedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=response_submitted_at,json=responseSubmittedAt,proto3,oneof" json:"response_submitted_at,omitempty"`
	ResolvedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=resolved_at,json=resolvedAt,proto3,oneof" json:"resolved_at,omitempty"`
	// Evidence and response (read-only - merchants respond via North portal)
	EvidenceFileUrls []string               `protobuf:"bytes,16,rep,name=evidence_file_urls,json=evidenceFileUrls,proto3" json:"evidence_file_urls,omitempty"` // File URLs if North API provides them
	ResponseText     *string                `protobuf:"bytes,17,opt,name=response_text,json=responseText,proto3,oneof" json:"response_text,omitempty"`         // Response text if submitted via North portal
	InternalNotes    *string                `protobuf:"bytes,18,opt,name=internal_notes,json=internalNotes,proto3,oneof" json:"internal_notes,omitempty"`      // Internal notes (local tracking only)
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chargeback) Reset() {
	*x = Chargeback{}
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chargeback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chargeback) ProtoMessage() {}

func (x *Chargeback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chargeback_v1_chargeback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chargeback.ProtoReflect.Descriptor instead.
func (*Chargeback) Descriptor() ([]byte, []int) {
	return file_proto_chargeback_v1_chargeback_proto_rawDescGZIP(), []int{3}
}

func (x *Chargeback) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chargeback) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Chargeback) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Chargeback) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Chargeback) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

func (x *Chargeback) GetDisputeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DisputeDate
	}
	return nil
}

func (x *Chargeback) GetChargebackDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargebackDate
	}
	return nil
}

func (x *Chargeback) GetChargebackAmount() string {
	if x != nil {
		return x.ChargebackAmount
	}
	return ""
}

func (x *Chargeback) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Chargeback) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *Chargeback) GetReasonDescription() string {
	if x != nil {
		return x.ReasonDescription
	}
	return ""
}

func (x *Chargeback) GetStatus() ChargebackStatus {
	if x != nil {
		return x.Status
	}
	return ChargebackStatus_CHARGEBACK_STATUS_UNSPECIFIED
}

func (x *Chargeback) GetRespondByDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondByDate
	}
	return nil
}

func (x *Chargeback) GetResponseSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResponseSubmittedAt
	}
	return nil
}

func (x *Chargeback) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Chargeback) GetEvidenceFileUrls() []string {
	if x != nil {
		return x.EvidenceFileUrls
	}
	return nil
}

func (x *Chargeback) GetResponseText() string {
	if x != nil && x.ResponseText != nil {
		return *x.ResponseText
	}
	return ""
}

func (x *Chargeback) GetInternalNotes() string {
	if x != nil && x.InternalNotes != nil {
		return *x.InternalNotes
	}
	return ""
}

func (x *Chargeback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chargeback) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_chargeback_v1_chargeback_proto protoreflect.FileDescriptor

const file_proto_chargeback_v1_chargeback_proto_rawDesc = "" +
	"\n" +
	"$proto/chargeback/v1/chargeback.proto\x12\rchargeback.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x14GetChargebackRequest\x12#\n" +
	"\rchargeback_id\x18\x01 \x01(\tR\fchargebackId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"\xcd\x03\n" +
	"\x16ListChargebacksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tH\x00R\n" +
	"customerId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\tH\x01R\agroupId\x88\x01\x01\x12<\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.chargeback.v1.ChargebackStatusH\x02R\x06status\x88\x01\x01\x12K\n" +
	"\x11dispute_date_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x0fdisputeDateFrom\x88\x01\x01\x12G\n" +
	"\x0fdispute_date_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\rdisputeDateTo\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offsetB\x0e\n" +
	"\f_customer_idB\v\n" +
	"\t_group_idB\t\n" +
	"\a_statusB\x14\n" +
	"\x12_dispute_date_fromB\x12\n" +
	"\x10_dispute_date_to\"w\n" +
	"\x17ListChargebacksResponse\x12;\n" +
	"\vchargebacks\x18\x01 \x03(\v2\x19.chargeback.v1.ChargebackR\vchargebacks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa7\b\n" +
	"\n" +
	"Chargeback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vcase_number\x18\x05 \x01(\tR\n" +
	"caseNumber\x12=\n" +
	"\fdispute_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdisputeDate\x12C\n" +
	"\x0fchargeback_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0echargebackDate\x12+\n" +
	"\x11chargeback_amount\x18\b \x01(\tR\x10chargebackAmount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x1f\n" +
	"\vreason_code\x18\n" +
	" \x01(\tR\n" +
	"reasonCode\x12-\n" +
	"\x12reason_description\x18\v \x01(\tR\x11reasonDescription\x127\n" +
	"\x06status\x18\f \x01(\x0e2\x1f.chargeback.v1.ChargebackStatusR\x06status\x12G\n" +
	"\x0frespond_by_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rrespondByDate\x88\x01\x01\x12S\n" +
	"\x15response_submitted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x13responseSubmittedAt\x88\x01\x01\x12@\n" +
	"\vresolved_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x02R\n" +
	"resolvedAt\x88\x01\x01\x12,\n" +
	"\x12evidence_file_urls\x18\x10 \x03(\tR\x10evidenceFileUrls\x12(\n" +
	"\rresponse_text\x18\x11 \x01(\tH\x03R\fresponseText\x88\x01\x01\x12*\n" +
	"\x0einternal_notes\x18\x12 \x01(\tH\x04R\rinternalNotes\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x12\n" +
	"\x10_respond_by_dateB\x18\n" +
	"\x16_response_submitted_atB\x0e\n" +
	"\f_resolved_atB\x10\n" +
	"\x0e_response_textB\x11\n" +
	"\x0f_internal_notes*\xe7\x01\n" +
	"\x10ChargebackStatus\x12!\n" +
	"\x1dCHARGEBACK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHARGEBACK_STATUS_NEW\x10\x01\x12\x1d\n" +
	"\x19CHARGEBACK_STATUS_PENDING\x10\x02\x12\x1f\n" +
	"\x1bCHARGEBACK_STATUS_RESPONDED\x10\x03\x12\x19\n" +
	"\x15CHARGEBACK_STATUS_WON\x10\x04\x12\x1a\n" +
	"\x16CHARGEBACK_STATUS_LOST\x10\x05\x12\x1e\n" +
	"\x1aCHARGEBACK_STATUS_ACCEPTED\x10\x062\xc6\x01\n" +
	"\x11ChargebackService\x12O\n" +
	"\rGetChargeback\x12#.chargeback.v1.GetChargebackRequest\x1a\x19.chargeback.v1.Chargeback\x12`\n" +
	"\x0fListChargebacks\x12%.chargeback.v1.ListChargebacksRequest\x1a&.chargeback.v1.ListChargebacksResponseBHZFgithub.com/kevin07696/payment-service/proto/chargeback/v1;chargebackv1b\x06proto3"

var (
	file_proto_chargeback_v1_chargeback_proto_rawDescOnce sync.Once
	file_proto_chargeback_v1_chargeback_proto_rawDescData []byte
)

func file_proto_chargeback_v1_chargeback_proto_rawDescGZIP() []byte {
	file_proto_chargeback_v1_chargeback_proto_rawDescOnce.Do(func() {
		file_proto_chargeback_v1_chargeback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chargeback_v1_chargeback_proto_rawDesc), len(file_proto_chargeback_v1_chargeback_proto_rawDesc)))
	})
	return file_proto_chargeback_v1_chargeback_proto_rawDescData
}

var file_proto_chargeback_v1_chargeback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chargeback_v1_chargeback_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_chargeback_v1_chargeback_proto_goTypes = []any{
	(ChargebackStatus)(0),           // 0: chargeback.v1.ChargebackStatus
	(*GetChargebackRequest)(nil),    // 1: chargeback.v1.GetChargebackRequest
	(*ListChargebacksRequest)(nil),  // 2: chargeback.v1.ListChargebacksRequest
	(*ListChargebacksResponse)(nil), // 3: chargeback.v1.ListChargebacksResponse
	(*Chargeback)(nil),              // 4: chargeback.v1.Chargeback
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_proto_chargeback_v1_chargeback_proto_depIdxs = []int32{
	0,  // 0: chargeback.v1.ListChargebacksRequest.status:type_name -> chargeback.v1.ChargebackStatus
	5,  // 1: chargeback.v1.ListChargebacksRequest.dispute_date_from:type_name -> google.protobuf.Timestamp
	5,  // 2: chargeback.v1.ListChargebacksRequest.dispute_date_to:type_name -> google.protobuf.Timestamp
	4,  // 3: chargeback.v1.ListChargebacksResponse.chargebacks:type_name -> chargeback.v1.Chargeback
	5,  // 4: chargeback.v1.Chargeback.dispute_date:type_name -> google.protobuf.Timestamp
	5,  // 5: chargeback.v1.Chargeback.chargeback_date:type_name -> google.protobuf.Timestamp
	0,  // 6: chargeback.v1.Chargeback.status:type_name -> chargeback.v1.ChargebackStatus
	5,  // 7: chargeback.v1.Chargeback.respond_by_date:type_name -> google.protobuf.Timestamp
	5,  // 8: chargeback.v1.Chargeback.response_submitted_at:type_name -> google.protobuf.Timestamp
	5,  // 9: chargeback.v1.Chargeback.resolved_at:type_name -> google.protobuf.Timestamp
	5,  // 10: chargeback.v1.Chargeback.created_at:type_name -> google.protobuf.Timestamp
	5,  // 11: chargeback.v1.Chargeback.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 12: chargeback.v1.ChargebackService.GetChargeback:input_type -> chargeback.v1.GetChargebackRequest
	2,  // 13: chargeback.v1.ChargebackService.ListChargebacks:input_type -> chargeback.v1.ListChargebacksRequest
	4,  // 14: chargeback.v1.ChargebackService.GetChargeback:output_type -> chargeback.v1.Chargeback
	3,  // 15: chargeback.v1.ChargebackService.ListChargebacks:output_type -> chargeback.v1.ListChargebacksResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_chargeback_v1_chargeback_proto_init() }
func file_proto_chargeback_v1_chargeback_proto_init() {
	if File_proto_chargeback_v1_chargeback_proto != nil {
		return
	}
	file_proto_chargeback_v1_chargeback_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_chargeback_v1_chargeback_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chargeback_v1_chargeback_proto_rawDesc), len(file_proto_chargeback_v1_chargeback_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chargeback_v1_chargeback_proto_goTypes,
		DependencyIndexes: file_proto_chargeback_v1_chargeback_proto_depIdxs,
		EnumInfos:         file_proto_chargeback_v1_chargeback_proto_enumTypes,
		MessageInfos:      file_proto_chargeback_v1_chargeback_proto_msgTypes,
	}.Build()
	File_proto_chargeback_v1_chargeback_proto = out.File
	file_proto_chargeback_v1_chargeback_proto_goTypes = nil
	file_proto_chargeback_v1_chargeback_proto_depIdxs = nil
}
