// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/chargeback/v1/chargeback.proto

package chargebackv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kevin07696/payment-service/proto/chargeback/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChargebackServiceName is the fully-qualified name of the ChargebackService service.
	ChargebackServiceName = "chargeback.v1.ChargebackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChargebackServiceGetChargebackProcedure is the fully-qualified name of the ChargebackService's
	// GetChargeback RPC.
	ChargebackServiceGetChargebackProcedure = "/chargeback.v1.ChargebackService/GetChargeback"
	// ChargebackServiceListChargebacksProcedure is the fully-qualified name of the ChargebackService's
	// ListChargebacks RPC.
	ChargebackServiceListChargebacksProcedure = "/chargeback.v1.ChargebackService/ListChargebacks"
)

// ChargebackServiceClient is a client for the chargeback.v1.ChargebackService service.
type ChargebackServiceClient interface {
	// GetChargeback retrieves a specific chargeback by ID
	GetChargeback(context.Context, *connect.Request[v1.GetChargebackRequest]) (*connect.Response[v1.Chargeback], error)
	// ListChargebacks lists chargebacks with filters
	ListChargebacks(context.Context, *connect.Request[v1.ListChargebacksRequest]) (*connect.Response[v1.ListChargebacksResponse], error)
}

// NewChargebackServiceClient constructs a client for the chargeback.v1.ChargebackService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChargebackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChargebackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chargebackServiceMethods := v1.File_proto_chargeback_v1_chargeback_proto.Services().ByName("ChargebackService").Methods()
	return &chargebackServiceClient{
		getChargeback: connect.NewClient[v1.GetChargebackRequest, v1.Chargeback](
			httpClient,
			baseURL+ChargebackServiceGetChargebackProcedure,
			connect.WithSchema(chargebackServiceMethods.ByName("GetChargeback")),
			connect.WithClientOptions(opts...),
		),
		listChargebacks: connect.NewClient[v1.ListChargebacksRequest, v1.ListChargebacksResponse](
			httpClient,
			baseURL+ChargebackServiceListChargebacksProcedure,
			connect.WithSchema(chargebackServiceMethods.ByName("ListChargebacks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chargebackServiceClient implements ChargebackServiceClient.
type chargebackServiceClient struct {
	getChargeback   *connect.Client[v1.GetChargebackRequest, v1.Chargeback]
	listChargebacks *connect.Client[v1.ListChargebacksRequest, v1.ListChargebacksResponse]
}

// GetChargeback calls chargeback.v1.ChargebackService.GetChargeback.
func (c *chargebackServiceClient) GetChargeback(ctx context.Context, req *connect.Request[v1.GetChargebackRequest]) (*connect.Response[v1.Chargeback], error) {
	return c.getChargeback.CallUnary(ctx, req)
}

// ListChargebacks calls chargeback.v1.ChargebackService.ListChargebacks.
func (c *chargebackServiceClient) ListChargebacks(ctx context.Context, req *connect.Request[v1.ListChargebacksRequest]) (*connect.Response[v1.ListChargebacksResponse], error) {
	return c.listChargebacks.CallUnary(ctx, req)
}

// ChargebackServiceHandler is an implementation of the chargeback.v1.ChargebackService service.
type ChargebackServiceHandler interface {
	// GetChargeback retrieves a specific chargeback by ID
	GetChargeback(context.Context, *connect.Request[v1.GetChargebackRequest]) (*connect.Response[v1.Chargeback], error)
	// ListChargebacks lists chargebacks with filters
	ListChargebacks(context.Context, *connect.Request[v1.ListChargebacksRequest]) (*connect.Response[v1.ListChargebacksResponse], error)
}

// NewChargebackServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChargebackServiceHandler(svc ChargebackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chargebackServiceMethods := v1.File_proto_chargeback_v1_chargeback_proto.Services().ByName("ChargebackService").Methods()
	chargebackServiceGetChargebackHandler := connect.NewUnaryHandler(
		ChargebackServiceGetChargebackProcedure,
		svc.GetChargeback,
		connect.WithSchema(chargebackServiceMethods.ByName("GetChargeback")),
		connect.WithHandlerOptions(opts...),
	)
	chargebackServiceListChargebacksHandler := connect.NewUnaryHandler(
		ChargebackServiceListChargebacksProcedure,
		svc.ListChargebacks,
		connect.WithSchema(chargebackServiceMethods.ByName("ListChargebacks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chargeback.v1.ChargebackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChargebackServiceGetChargebackProcedure:
			chargebackServiceGetChargebackHandler.ServeHTTP(w, r)
		case ChargebackServiceListChargebacksProcedure:
			chargebackServiceListChargebacksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChargebackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChargebackServiceHandler struct{}

func (UnimplementedChargebackServiceHandler) GetChargeback(context.Context, *connect.Request[v1.GetChargebackRequest]) (*connect.Response[v1.Chargeback], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chargeback.v1.ChargebackService.GetChargeback is not implemented"))
}

func (UnimplementedChargebackServiceHandler) ListChargebacks(context.Context, *connect.Request[v1.ListChargebacksRequest]) (*connect.Response[v1.ListChargebacksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chargeback.v1.ChargebackService.ListChargebacks is not implemented"))
}
