// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/payment_method/v1/payment_method.proto

package paymentmethodv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kevin07696/payment-service/proto/payment_method/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentMethodServiceName is the fully-qualified name of the PaymentMethodService service.
	PaymentMethodServiceName = "payment_method.v1.PaymentMethodService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentMethodServiceGetPaymentMethodProcedure is the fully-qualified name of the
	// PaymentMethodService's GetPaymentMethod RPC.
	PaymentMethodServiceGetPaymentMethodProcedure = "/payment_method.v1.PaymentMethodService/GetPaymentMethod"
	// PaymentMethodServiceListPaymentMethodsProcedure is the fully-qualified name of the
	// PaymentMethodService's ListPaymentMethods RPC.
	PaymentMethodServiceListPaymentMethodsProcedure = "/payment_method.v1.PaymentMethodService/ListPaymentMethods"
	// PaymentMethodServiceUpdatePaymentMethodStatusProcedure is the fully-qualified name of the
	// PaymentMethodService's UpdatePaymentMethodStatus RPC.
	PaymentMethodServiceUpdatePaymentMethodStatusProcedure = "/payment_method.v1.PaymentMethodService/UpdatePaymentMethodStatus"
	// PaymentMethodServiceDeletePaymentMethodProcedure is the fully-qualified name of the
	// PaymentMethodService's DeletePaymentMethod RPC.
	PaymentMethodServiceDeletePaymentMethodProcedure = "/payment_method.v1.PaymentMethodService/DeletePaymentMethod"
	// PaymentMethodServiceSetDefaultPaymentMethodProcedure is the fully-qualified name of the
	// PaymentMethodService's SetDefaultPaymentMethod RPC.
	PaymentMethodServiceSetDefaultPaymentMethodProcedure = "/payment_method.v1.PaymentMethodService/SetDefaultPaymentMethod"
	// PaymentMethodServiceVerifyACHAccountProcedure is the fully-qualified name of the
	// PaymentMethodService's VerifyACHAccount RPC.
	PaymentMethodServiceVerifyACHAccountProcedure = "/payment_method.v1.PaymentMethodService/VerifyACHAccount"
	// PaymentMethodServiceStoreACHAccountProcedure is the fully-qualified name of the
	// PaymentMethodService's StoreACHAccount RPC.
	PaymentMethodServiceStoreACHAccountProcedure = "/payment_method.v1.PaymentMethodService/StoreACHAccount"
	// PaymentMethodServiceUpdatePaymentMethodProcedure is the fully-qualified name of the
	// PaymentMethodService's UpdatePaymentMethod RPC.
	PaymentMethodServiceUpdatePaymentMethodProcedure = "/payment_method.v1.PaymentMethodService/UpdatePaymentMethod"
)

// PaymentMethodServiceClient is a client for the payment_method.v1.PaymentMethodService service.
type PaymentMethodServiceClient interface {
	// GetPaymentMethod retrieves a specific payment method
	GetPaymentMethod(context.Context, *connect.Request[v1.GetPaymentMethodRequest]) (*connect.Response[v1.PaymentMethod], error)
	// ListPaymentMethods lists all payment methods for a customer
	ListPaymentMethods(context.Context, *connect.Request[v1.ListPaymentMethodsRequest]) (*connect.Response[v1.ListPaymentMethodsResponse], error)
	// UpdatePaymentMethodStatus updates the active status of a payment method
	UpdatePaymentMethodStatus(context.Context, *connect.Request[v1.UpdatePaymentMethodStatusRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// DeletePaymentMethod soft deletes a payment method (sets deleted_at)
	DeletePaymentMethod(context.Context, *connect.Request[v1.DeletePaymentMethodRequest]) (*connect.Response[v1.DeletePaymentMethodResponse], error)
	// SetDefaultPaymentMethod marks a payment method as default
	SetDefaultPaymentMethod(context.Context, *connect.Request[v1.SetDefaultPaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// VerifyACHAccount sends pre-note for ACH verification
	VerifyACHAccount(context.Context, *connect.Request[v1.VerifyACHAccountRequest]) (*connect.Response[v1.VerifyACHAccountResponse], error)
	// StoreACHAccount creates ACH Storage BRIC and sends pre-note for verification
	// Use case: Customer adds bank account for recurring payments
	StoreACHAccount(context.Context, *connect.Request[v1.StoreACHAccountRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// UpdatePaymentMethod updates metadata only (billing info, nickname)
	// Does NOT support changing account/routing numbers - create new payment method instead
	UpdatePaymentMethod(context.Context, *connect.Request[v1.UpdatePaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
}

// NewPaymentMethodServiceClient constructs a client for the payment_method.v1.PaymentMethodService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentMethodServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentMethodServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paymentMethodServiceMethods := v1.File_proto_payment_method_v1_payment_method_proto.Services().ByName("PaymentMethodService").Methods()
	return &paymentMethodServiceClient{
		getPaymentMethod: connect.NewClient[v1.GetPaymentMethodRequest, v1.PaymentMethod](
			httpClient,
			baseURL+PaymentMethodServiceGetPaymentMethodProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("GetPaymentMethod")),
			connect.WithClientOptions(opts...),
		),
		listPaymentMethods: connect.NewClient[v1.ListPaymentMethodsRequest, v1.ListPaymentMethodsResponse](
			httpClient,
			baseURL+PaymentMethodServiceListPaymentMethodsProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("ListPaymentMethods")),
			connect.WithClientOptions(opts...),
		),
		updatePaymentMethodStatus: connect.NewClient[v1.UpdatePaymentMethodStatusRequest, v1.PaymentMethodResponse](
			httpClient,
			baseURL+PaymentMethodServiceUpdatePaymentMethodStatusProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("UpdatePaymentMethodStatus")),
			connect.WithClientOptions(opts...),
		),
		deletePaymentMethod: connect.NewClient[v1.DeletePaymentMethodRequest, v1.DeletePaymentMethodResponse](
			httpClient,
			baseURL+PaymentMethodServiceDeletePaymentMethodProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("DeletePaymentMethod")),
			connect.WithClientOptions(opts...),
		),
		setDefaultPaymentMethod: connect.NewClient[v1.SetDefaultPaymentMethodRequest, v1.PaymentMethodResponse](
			httpClient,
			baseURL+PaymentMethodServiceSetDefaultPaymentMethodProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("SetDefaultPaymentMethod")),
			connect.WithClientOptions(opts...),
		),
		verifyACHAccount: connect.NewClient[v1.VerifyACHAccountRequest, v1.VerifyACHAccountResponse](
			httpClient,
			baseURL+PaymentMethodServiceVerifyACHAccountProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("VerifyACHAccount")),
			connect.WithClientOptions(opts...),
		),
		storeACHAccount: connect.NewClient[v1.StoreACHAccountRequest, v1.PaymentMethodResponse](
			httpClient,
			baseURL+PaymentMethodServiceStoreACHAccountProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("StoreACHAccount")),
			connect.WithClientOptions(opts...),
		),
		updatePaymentMethod: connect.NewClient[v1.UpdatePaymentMethodRequest, v1.PaymentMethodResponse](
			httpClient,
			baseURL+PaymentMethodServiceUpdatePaymentMethodProcedure,
			connect.WithSchema(paymentMethodServiceMethods.ByName("UpdatePaymentMethod")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentMethodServiceClient implements PaymentMethodServiceClient.
type paymentMethodServiceClient struct {
	getPaymentMethod          *connect.Client[v1.GetPaymentMethodRequest, v1.PaymentMethod]
	listPaymentMethods        *connect.Client[v1.ListPaymentMethodsRequest, v1.ListPaymentMethodsResponse]
	updatePaymentMethodStatus *connect.Client[v1.UpdatePaymentMethodStatusRequest, v1.PaymentMethodResponse]
	deletePaymentMethod       *connect.Client[v1.DeletePaymentMethodRequest, v1.DeletePaymentMethodResponse]
	setDefaultPaymentMethod   *connect.Client[v1.SetDefaultPaymentMethodRequest, v1.PaymentMethodResponse]
	verifyACHAccount          *connect.Client[v1.VerifyACHAccountRequest, v1.VerifyACHAccountResponse]
	storeACHAccount           *connect.Client[v1.StoreACHAccountRequest, v1.PaymentMethodResponse]
	updatePaymentMethod       *connect.Client[v1.UpdatePaymentMethodRequest, v1.PaymentMethodResponse]
}

// GetPaymentMethod calls payment_method.v1.PaymentMethodService.GetPaymentMethod.
func (c *paymentMethodServiceClient) GetPaymentMethod(ctx context.Context, req *connect.Request[v1.GetPaymentMethodRequest]) (*connect.Response[v1.PaymentMethod], error) {
	return c.getPaymentMethod.CallUnary(ctx, req)
}

// ListPaymentMethods calls payment_method.v1.PaymentMethodService.ListPaymentMethods.
func (c *paymentMethodServiceClient) ListPaymentMethods(ctx context.Context, req *connect.Request[v1.ListPaymentMethodsRequest]) (*connect.Response[v1.ListPaymentMethodsResponse], error) {
	return c.listPaymentMethods.CallUnary(ctx, req)
}

// UpdatePaymentMethodStatus calls payment_method.v1.PaymentMethodService.UpdatePaymentMethodStatus.
func (c *paymentMethodServiceClient) UpdatePaymentMethodStatus(ctx context.Context, req *connect.Request[v1.UpdatePaymentMethodStatusRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return c.updatePaymentMethodStatus.CallUnary(ctx, req)
}

// DeletePaymentMethod calls payment_method.v1.PaymentMethodService.DeletePaymentMethod.
func (c *paymentMethodServiceClient) DeletePaymentMethod(ctx context.Context, req *connect.Request[v1.DeletePaymentMethodRequest]) (*connect.Response[v1.DeletePaymentMethodResponse], error) {
	return c.deletePaymentMethod.CallUnary(ctx, req)
}

// SetDefaultPaymentMethod calls payment_method.v1.PaymentMethodService.SetDefaultPaymentMethod.
func (c *paymentMethodServiceClient) SetDefaultPaymentMethod(ctx context.Context, req *connect.Request[v1.SetDefaultPaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return c.setDefaultPaymentMethod.CallUnary(ctx, req)
}

// VerifyACHAccount calls payment_method.v1.PaymentMethodService.VerifyACHAccount.
func (c *paymentMethodServiceClient) VerifyACHAccount(ctx context.Context, req *connect.Request[v1.VerifyACHAccountRequest]) (*connect.Response[v1.VerifyACHAccountResponse], error) {
	return c.verifyACHAccount.CallUnary(ctx, req)
}

// StoreACHAccount calls payment_method.v1.PaymentMethodService.StoreACHAccount.
func (c *paymentMethodServiceClient) StoreACHAccount(ctx context.Context, req *connect.Request[v1.StoreACHAccountRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return c.storeACHAccount.CallUnary(ctx, req)
}

// UpdatePaymentMethod calls payment_method.v1.PaymentMethodService.UpdatePaymentMethod.
func (c *paymentMethodServiceClient) UpdatePaymentMethod(ctx context.Context, req *connect.Request[v1.UpdatePaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return c.updatePaymentMethod.CallUnary(ctx, req)
}

// PaymentMethodServiceHandler is an implementation of the payment_method.v1.PaymentMethodService
// service.
type PaymentMethodServiceHandler interface {
	// GetPaymentMethod retrieves a specific payment method
	GetPaymentMethod(context.Context, *connect.Request[v1.GetPaymentMethodRequest]) (*connect.Response[v1.PaymentMethod], error)
	// ListPaymentMethods lists all payment methods for a customer
	ListPaymentMethods(context.Context, *connect.Request[v1.ListPaymentMethodsRequest]) (*connect.Response[v1.ListPaymentMethodsResponse], error)
	// UpdatePaymentMethodStatus updates the active status of a payment method
	UpdatePaymentMethodStatus(context.Context, *connect.Request[v1.UpdatePaymentMethodStatusRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// DeletePaymentMethod soft deletes a payment method (sets deleted_at)
	DeletePaymentMethod(context.Context, *connect.Request[v1.DeletePaymentMethodRequest]) (*connect.Response[v1.DeletePaymentMethodResponse], error)
	// SetDefaultPaymentMethod marks a payment method as default
	SetDefaultPaymentMethod(context.Context, *connect.Request[v1.SetDefaultPaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// VerifyACHAccount sends pre-note for ACH verification
	VerifyACHAccount(context.Context, *connect.Request[v1.VerifyACHAccountRequest]) (*connect.Response[v1.VerifyACHAccountResponse], error)
	// StoreACHAccount creates ACH Storage BRIC and sends pre-note for verification
	// Use case: Customer adds bank account for recurring payments
	StoreACHAccount(context.Context, *connect.Request[v1.StoreACHAccountRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
	// UpdatePaymentMethod updates metadata only (billing info, nickname)
	// Does NOT support changing account/routing numbers - create new payment method instead
	UpdatePaymentMethod(context.Context, *connect.Request[v1.UpdatePaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error)
}

// NewPaymentMethodServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentMethodServiceHandler(svc PaymentMethodServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentMethodServiceMethods := v1.File_proto_payment_method_v1_payment_method_proto.Services().ByName("PaymentMethodService").Methods()
	paymentMethodServiceGetPaymentMethodHandler := connect.NewUnaryHandler(
		PaymentMethodServiceGetPaymentMethodProcedure,
		svc.GetPaymentMethod,
		connect.WithSchema(paymentMethodServiceMethods.ByName("GetPaymentMethod")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceListPaymentMethodsHandler := connect.NewUnaryHandler(
		PaymentMethodServiceListPaymentMethodsProcedure,
		svc.ListPaymentMethods,
		connect.WithSchema(paymentMethodServiceMethods.ByName("ListPaymentMethods")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceUpdatePaymentMethodStatusHandler := connect.NewUnaryHandler(
		PaymentMethodServiceUpdatePaymentMethodStatusProcedure,
		svc.UpdatePaymentMethodStatus,
		connect.WithSchema(paymentMethodServiceMethods.ByName("UpdatePaymentMethodStatus")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceDeletePaymentMethodHandler := connect.NewUnaryHandler(
		PaymentMethodServiceDeletePaymentMethodProcedure,
		svc.DeletePaymentMethod,
		connect.WithSchema(paymentMethodServiceMethods.ByName("DeletePaymentMethod")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceSetDefaultPaymentMethodHandler := connect.NewUnaryHandler(
		PaymentMethodServiceSetDefaultPaymentMethodProcedure,
		svc.SetDefaultPaymentMethod,
		connect.WithSchema(paymentMethodServiceMethods.ByName("SetDefaultPaymentMethod")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceVerifyACHAccountHandler := connect.NewUnaryHandler(
		PaymentMethodServiceVerifyACHAccountProcedure,
		svc.VerifyACHAccount,
		connect.WithSchema(paymentMethodServiceMethods.ByName("VerifyACHAccount")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceStoreACHAccountHandler := connect.NewUnaryHandler(
		PaymentMethodServiceStoreACHAccountProcedure,
		svc.StoreACHAccount,
		connect.WithSchema(paymentMethodServiceMethods.ByName("StoreACHAccount")),
		connect.WithHandlerOptions(opts...),
	)
	paymentMethodServiceUpdatePaymentMethodHandler := connect.NewUnaryHandler(
		PaymentMethodServiceUpdatePaymentMethodProcedure,
		svc.UpdatePaymentMethod,
		connect.WithSchema(paymentMethodServiceMethods.ByName("UpdatePaymentMethod")),
		connect.WithHandlerOptions(opts...),
	)
	return "/payment_method.v1.PaymentMethodService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentMethodServiceGetPaymentMethodProcedure:
			paymentMethodServiceGetPaymentMethodHandler.ServeHTTP(w, r)
		case PaymentMethodServiceListPaymentMethodsProcedure:
			paymentMethodServiceListPaymentMethodsHandler.ServeHTTP(w, r)
		case PaymentMethodServiceUpdatePaymentMethodStatusProcedure:
			paymentMethodServiceUpdatePaymentMethodStatusHandler.ServeHTTP(w, r)
		case PaymentMethodServiceDeletePaymentMethodProcedure:
			paymentMethodServiceDeletePaymentMethodHandler.ServeHTTP(w, r)
		case PaymentMethodServiceSetDefaultPaymentMethodProcedure:
			paymentMethodServiceSetDefaultPaymentMethodHandler.ServeHTTP(w, r)
		case PaymentMethodServiceVerifyACHAccountProcedure:
			paymentMethodServiceVerifyACHAccountHandler.ServeHTTP(w, r)
		case PaymentMethodServiceStoreACHAccountProcedure:
			paymentMethodServiceStoreACHAccountHandler.ServeHTTP(w, r)
		case PaymentMethodServiceUpdatePaymentMethodProcedure:
			paymentMethodServiceUpdatePaymentMethodHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentMethodServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentMethodServiceHandler struct{}

func (UnimplementedPaymentMethodServiceHandler) GetPaymentMethod(context.Context, *connect.Request[v1.GetPaymentMethodRequest]) (*connect.Response[v1.PaymentMethod], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.GetPaymentMethod is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) ListPaymentMethods(context.Context, *connect.Request[v1.ListPaymentMethodsRequest]) (*connect.Response[v1.ListPaymentMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.ListPaymentMethods is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) UpdatePaymentMethodStatus(context.Context, *connect.Request[v1.UpdatePaymentMethodStatusRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.UpdatePaymentMethodStatus is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) DeletePaymentMethod(context.Context, *connect.Request[v1.DeletePaymentMethodRequest]) (*connect.Response[v1.DeletePaymentMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.DeletePaymentMethod is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) SetDefaultPaymentMethod(context.Context, *connect.Request[v1.SetDefaultPaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.SetDefaultPaymentMethod is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) VerifyACHAccount(context.Context, *connect.Request[v1.VerifyACHAccountRequest]) (*connect.Response[v1.VerifyACHAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.VerifyACHAccount is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) StoreACHAccount(context.Context, *connect.Request[v1.StoreACHAccountRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.StoreACHAccount is not implemented"))
}

func (UnimplementedPaymentMethodServiceHandler) UpdatePaymentMethod(context.Context, *connect.Request[v1.UpdatePaymentMethodRequest]) (*connect.Response[v1.PaymentMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment_method.v1.PaymentMethodService.UpdatePaymentMethod is not implemented"))
}
